modLoader="javafml"
loaderVersion="[47,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="pokefood"
version="1.2.4"
displayName="PokeFood"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pokefood"
logoFile="logo.png"
credits="Special thanks to the cobblemon community for the support"
authors="HultraFox"
description="The pokemon food mod."

[[dependencies.pokefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.pokefood]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

