modLoader="javafml"
loaderVersion="[43,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="pokefood"
version="1.2.2"
displayName="PokeFood"
credits="The cobblemon team and community"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pokefood"
logoFile="logo.png"
authors="HultraFox"
description="Food to be used with cobblemon (may contain traces of calcuim !)"

[[dependencies.pokefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




