
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.pokefood.init;

import net.pokefood.block.WhiteWineBlock;
import net.pokefood.block.TeaBlock;
import net.pokefood.block.SugarMelter9Block;
import net.pokefood.block.SugarMelter8Block;
import net.pokefood.block.SugarMelter7Block;
import net.pokefood.block.SugarMelter6Block;
import net.pokefood.block.SugarMelter5Block;
import net.pokefood.block.SugarMelter4Block;
import net.pokefood.block.SugarMelter3Block;
import net.pokefood.block.SugarMelter2Block;
import net.pokefood.block.SugarMelter1Block;
import net.pokefood.block.SugarMelter0Block;
import net.pokefood.block.RoseradeTeaBlock;
import net.pokefood.block.RoseWineBlock;
import net.pokefood.block.RiceStage5Block;
import net.pokefood.block.RiceStage4Block;
import net.pokefood.block.RiceStage3Block;
import net.pokefood.block.RiceStage2Block;
import net.pokefood.block.RiceStage1Block;
import net.pokefood.block.RiceStage0Block;
import net.pokefood.block.RestaurantSofaCorner9Block;
import net.pokefood.block.RestaurantSofaCorner8Block;
import net.pokefood.block.RestaurantSofaCorner7Block;
import net.pokefood.block.RestaurantSofaCorner6Block;
import net.pokefood.block.RestaurantSofaCorner5Block;
import net.pokefood.block.RestaurantSofaCorner4Block;
import net.pokefood.block.RestaurantSofaCorner3Block;
import net.pokefood.block.RestaurantSofaCorner2Block;
import net.pokefood.block.RestaurantSofaCorner1Block;
import net.pokefood.block.RestaurantSofaCorner15Block;
import net.pokefood.block.RestaurantSofaCorner14Block;
import net.pokefood.block.RestaurantSofaCorner13Block;
import net.pokefood.block.RestaurantSofaCorner12Block;
import net.pokefood.block.RestaurantSofaCorner11Block;
import net.pokefood.block.RestaurantSofaCorner10Block;
import net.pokefood.block.RestaurantSofaCorner0Block;
import net.pokefood.block.RestaurantSofa9Block;
import net.pokefood.block.RestaurantSofa8Block;
import net.pokefood.block.RestaurantSofa7Block;
import net.pokefood.block.RestaurantSofa6Block;
import net.pokefood.block.RestaurantSofa5Block;
import net.pokefood.block.RestaurantSofa4Block;
import net.pokefood.block.RestaurantSofa3Block;
import net.pokefood.block.RestaurantSofa2Block;
import net.pokefood.block.RestaurantSofa1Block;
import net.pokefood.block.RestaurantSofa15Block;
import net.pokefood.block.RestaurantSofa14Block;
import net.pokefood.block.RestaurantSofa13Block;
import net.pokefood.block.RestaurantSofa12Block;
import net.pokefood.block.RestaurantSofa11Block;
import net.pokefood.block.RestaurantSofa10Block;
import net.pokefood.block.RestaurantSofa0Block;
import net.pokefood.block.RedWineBlock;
import net.pokefood.block.PlateBlockBlock;
import net.pokefood.block.PackTeaRoseradeBlock;
import net.pokefood.block.PackTeaBlock;
import net.pokefood.block.PackTeaBlackBlock;
import net.pokefood.block.PackPopBlock;
import net.pokefood.block.PackLemonadeBlock;
import net.pokefood.block.PackLatteBlock;
import net.pokefood.block.PackEmptyBlock;
import net.pokefood.block.PackCoffeeBlock;
import net.pokefood.block.PackCherryBlock;
import net.pokefood.block.PackApriYBlock;
import net.pokefood.block.PackApriWBlock;
import net.pokefood.block.PackApriRBlock;
import net.pokefood.block.PackApriPBlock;
import net.pokefood.block.PackApriGBlock;
import net.pokefood.block.PackApriDBlock;
import net.pokefood.block.PackApriBBlock;
import net.pokefood.block.OnionPlantBlock;
import net.pokefood.block.MortarAndPestle9Block;
import net.pokefood.block.MortarAndPestle8Block;
import net.pokefood.block.MortarAndPestle7Block;
import net.pokefood.block.MortarAndPestle6Block;
import net.pokefood.block.MortarAndPestle5Block;
import net.pokefood.block.MortarAndPestle4Block;
import net.pokefood.block.MortarAndPestle3Block;
import net.pokefood.block.MortarAndPestle2Block;
import net.pokefood.block.MortarAndPestle1Block;
import net.pokefood.block.MortarAndPestle11Block;
import net.pokefood.block.MortarAndPestle10Block;
import net.pokefood.block.MortarAndPestle0Block;
import net.pokefood.block.MixerYellowBlock;
import net.pokefood.block.MixerRedBlock;
import net.pokefood.block.MixerPinkBlock;
import net.pokefood.block.MixerGreenBlock;
import net.pokefood.block.MixerBlueBlock;
import net.pokefood.block.MaltBlock;
import net.pokefood.block.LettuceWildBlock;
import net.pokefood.block.LettucePlantBlock;
import net.pokefood.block.LemonadeBlock;
import net.pokefood.block.LemonStage6Block;
import net.pokefood.block.LemonStage5Block;
import net.pokefood.block.LemonStage4Block;
import net.pokefood.block.LemonStage3Block;
import net.pokefood.block.LemonStage2Block;
import net.pokefood.block.LemonStage1Block;
import net.pokefood.block.LemonStage0Block;
import net.pokefood.block.LeekPlantBlock;
import net.pokefood.block.LatteBlock;
import net.pokefood.block.Lamp0OnBlock;
import net.pokefood.block.Lamp0OffBlock;
import net.pokefood.block.KegFunnelBlock;
import net.pokefood.block.KegBlock;
import net.pokefood.block.IceCreamMakerBlock;
import net.pokefood.block.IceCreamExtentionBlock;
import net.pokefood.block.HeaterBlock;
import net.pokefood.block.GreenTeaPlantBlock;
import net.pokefood.block.GrapeVine2Block;
import net.pokefood.block.GrapeVine1Block;
import net.pokefood.block.GrapeVine0Block;
import net.pokefood.block.GrapeSproutBlock;
import net.pokefood.block.GrapeSprout2Block;
import net.pokefood.block.GrapeSprout1Block;
import net.pokefood.block.FryerBlock;
import net.pokefood.block.FreshWaterBlock;
import net.pokefood.block.DisplaySodaTeaRoseradeBlock;
import net.pokefood.block.DisplaySodaTeaBlock;
import net.pokefood.block.DisplaySodaTeaBlackBlock;
import net.pokefood.block.DisplaySodaSombrineBlock;
import net.pokefood.block.DisplaySodaSombradeBlock;
import net.pokefood.block.DisplaySodaPopBlock;
import net.pokefood.block.DisplaySodaLemonadeBlock;
import net.pokefood.block.DisplaySodaCherryBlock;
import net.pokefood.block.DisplaySodaApriYBlock;
import net.pokefood.block.DisplaySodaApriWBlock;
import net.pokefood.block.DisplaySodaApriRBlock;
import net.pokefood.block.DisplaySodaApriPBlock;
import net.pokefood.block.DisplaySodaApriGBlock;
import net.pokefood.block.DisplaySodaApriDBlock;
import net.pokefood.block.DisplaySodaApriBBlock;
import net.pokefood.block.DisplayCasePuffs9Block;
import net.pokefood.block.DisplayCasePuffs8Block;
import net.pokefood.block.DisplayCasePuffs7Block;
import net.pokefood.block.DisplayCasePuffs6Block;
import net.pokefood.block.DisplayCasePuffs5Block;
import net.pokefood.block.DisplayCasePuffs4Block;
import net.pokefood.block.DisplayCasePuffs3Block;
import net.pokefood.block.DisplayCasePuffs2Block;
import net.pokefood.block.DisplayCasePuffs1Block;
import net.pokefood.block.DisplayCasePuffs14Block;
import net.pokefood.block.DisplayCasePuffs13Block;
import net.pokefood.block.DisplayCasePuffs12Block;
import net.pokefood.block.DisplayCasePuffs11Block;
import net.pokefood.block.DisplayCasePuffs10Block;
import net.pokefood.block.DisplayCasePuffs0Block;
import net.pokefood.block.DisplayCasePoffin9Block;
import net.pokefood.block.DisplayCasePoffin8Block;
import net.pokefood.block.DisplayCasePoffin7Block;
import net.pokefood.block.DisplayCasePoffin6Block;
import net.pokefood.block.DisplayCasePoffin5Block;
import net.pokefood.block.DisplayCasePoffin4Block;
import net.pokefood.block.DisplayCasePoffin3Block;
import net.pokefood.block.DisplayCasePoffin2Block;
import net.pokefood.block.DisplayCasePoffin1Block;
import net.pokefood.block.DisplayCasePoffin0Block;
import net.pokefood.block.DisplayCaseEmptyBlock;
import net.pokefood.block.CurryPotBlock;
import net.pokefood.block.CupUncookedBlockBlock;
import net.pokefood.block.CupBlockTeaBlock;
import net.pokefood.block.CupBlockRoseradeTeaBlock;
import net.pokefood.block.CupBlockLemonadeBlock;
import net.pokefood.block.CupBlockLatteBlock;
import net.pokefood.block.CupBlockFreshWaterBlock;
import net.pokefood.block.CupBlockCoffeeIcedBlock;
import net.pokefood.block.CupBlockCoffeeBlock;
import net.pokefood.block.CupBlockCherryInfusionBlock;
import net.pokefood.block.CupBlockBlock;
import net.pokefood.block.CupBlockBlackTeaBlock;
import net.pokefood.block.CupBlockApriYBlock;
import net.pokefood.block.CupBlockApriWBlock;
import net.pokefood.block.CupBlockApriRBlock;
import net.pokefood.block.CupBlockApriPBlock;
import net.pokefood.block.CupBlockApriGBlock;
import net.pokefood.block.CupBlockApriDBlock;
import net.pokefood.block.CupBlockApriBBlock;
import net.pokefood.block.CrystalizedSugarBlock9Block;
import net.pokefood.block.CrystalizedSugarBlock8Block;
import net.pokefood.block.CrystalizedSugarBlock7Block;
import net.pokefood.block.CrystalizedSugarBlock6Block;
import net.pokefood.block.CrystalizedSugarBlock5Block;
import net.pokefood.block.CrystalizedSugarBlock4Block;
import net.pokefood.block.CrystalizedSugarBlock3Block;
import net.pokefood.block.CrystalizedSugarBlock2Block;
import net.pokefood.block.CrystalizedSugarBlock1Block;
import net.pokefood.block.CrystalizedSugarBlock15Block;
import net.pokefood.block.CrystalizedSugarBlock14Block;
import net.pokefood.block.CrystalizedSugarBlock13Block;
import net.pokefood.block.CrystalizedSugarBlock12Block;
import net.pokefood.block.CrystalizedSugarBlock11Block;
import net.pokefood.block.CrystalizedSugarBlock10Block;
import net.pokefood.block.CrystalizedSugarBlock0Block;
import net.pokefood.block.CrepeMakerBlock;
import net.pokefood.block.CoolerYellowBlock;
import net.pokefood.block.CoolerRedBlock;
import net.pokefood.block.CoolerPinkBlock;
import net.pokefood.block.CoolerGreenBlock;
import net.pokefood.block.CoolerBlueBlock;
import net.pokefood.block.CookingPotBlock;
import net.pokefood.block.ConeDisplayBlock;
import net.pokefood.block.CoffeeTable9Block;
import net.pokefood.block.CoffeeTable8Block;
import net.pokefood.block.CoffeeTable7Block;
import net.pokefood.block.CoffeeTable6Block;
import net.pokefood.block.CoffeeTable5Block;
import net.pokefood.block.CoffeeTable4Block;
import net.pokefood.block.CoffeeTable3Block;
import net.pokefood.block.CoffeeTable2Block;
import net.pokefood.block.CoffeeTable1Block;
import net.pokefood.block.CoffeeTable11Block;
import net.pokefood.block.CoffeeTable10Block;
import net.pokefood.block.CoffeeTable0Block;
import net.pokefood.block.CoffeeMakerCookingBlock;
import net.pokefood.block.CoffeeMakerCookedBlock;
import net.pokefood.block.CoffeeMakerBlock;
import net.pokefood.block.CoffeeIcedBlock;
import net.pokefood.block.CoffeeBlock;
import net.pokefood.block.CidronadeBlock;
import net.pokefood.block.CherryInfusionBlock;
import net.pokefood.block.CherryCalcuimBeerBlock;
import net.pokefood.block.CheeseTQ5Block;
import net.pokefood.block.CheeseTQ4Block;
import net.pokefood.block.CheeseTQ3Block;
import net.pokefood.block.CheeseTQ2Block;
import net.pokefood.block.CheeseTQ1Block;
import net.pokefood.block.CheeseTQ0Block;
import net.pokefood.block.CheeseQ5Block;
import net.pokefood.block.CheeseQ4Block;
import net.pokefood.block.CheeseQ3Block;
import net.pokefood.block.CheeseQ2Block;
import net.pokefood.block.CheeseQ1Block;
import net.pokefood.block.CheeseQ0Block;
import net.pokefood.block.CheeseMoldBlock;
import net.pokefood.block.CheeseH5Block;
import net.pokefood.block.CheeseH4Block;
import net.pokefood.block.CheeseH3Block;
import net.pokefood.block.CheeseH2Block;
import net.pokefood.block.CheeseH1Block;
import net.pokefood.block.CheeseH0Block;
import net.pokefood.block.CheeseFull5Block;
import net.pokefood.block.CheeseFull4Block;
import net.pokefood.block.CheeseFull3Block;
import net.pokefood.block.CheeseFull2Block;
import net.pokefood.block.CheeseFull1Block;
import net.pokefood.block.CheeseFull0Block;
import net.pokefood.block.Chair1Block;
import net.pokefood.block.Chair0Block;
import net.pokefood.block.CardboardBoxBlock;
import net.pokefood.block.CarbonizerBottleBlock;
import net.pokefood.block.CandyMachine9Block;
import net.pokefood.block.CandyMachine8Block;
import net.pokefood.block.CandyMachine7Block;
import net.pokefood.block.CandyMachine6Block;
import net.pokefood.block.CandyMachine5Block;
import net.pokefood.block.CandyMachine4Block;
import net.pokefood.block.CandyMachine3Block;
import net.pokefood.block.CandyMachine2Block;
import net.pokefood.block.CandyMachine1Block;
import net.pokefood.block.CandyMachine15Block;
import net.pokefood.block.CandyMachine14Block;
import net.pokefood.block.CandyMachine13Block;
import net.pokefood.block.CandyMachine12Block;
import net.pokefood.block.CandyMachine11Block;
import net.pokefood.block.CandyMachine10Block;
import net.pokefood.block.CandyMachine0Block;
import net.pokefood.block.CandyBoxBlock;
import net.pokefood.block.CalcuimEmptyB9Block;
import net.pokefood.block.CalcuimEmptyB8Block;
import net.pokefood.block.CalcuimEmptyB7Block;
import net.pokefood.block.CalcuimEmptyB6Block;
import net.pokefood.block.CalcuimEmptyB5Block;
import net.pokefood.block.CalcuimEmptyB4Block;
import net.pokefood.block.CalcuimEmptyB3Block;
import net.pokefood.block.CalcuimEmptyB2Block;
import net.pokefood.block.CalcuimEmptyB1Block;
import net.pokefood.block.CalcuimEmptyB15Block;
import net.pokefood.block.CalcuimEmptyB14Block;
import net.pokefood.block.CalcuimEmptyB13Block;
import net.pokefood.block.CalcuimEmptyB12Block;
import net.pokefood.block.CalcuimEmptyB11Block;
import net.pokefood.block.CalcuimEmptyB10Block;
import net.pokefood.block.CalcuimEmptyB0Block;
import net.pokefood.block.CalcuimCropBlock;
import net.pokefood.block.CalcuimB9Block;
import net.pokefood.block.CalcuimB8Block;
import net.pokefood.block.CalcuimB7Block;
import net.pokefood.block.CalcuimB6Block;
import net.pokefood.block.CalcuimB5Block;
import net.pokefood.block.CalcuimB4Block;
import net.pokefood.block.CalcuimB3Block;
import net.pokefood.block.CalcuimB2Block;
import net.pokefood.block.CalcuimB1Block;
import net.pokefood.block.CalcuimB15Block;
import net.pokefood.block.CalcuimB14Block;
import net.pokefood.block.CalcuimB13Block;
import net.pokefood.block.CalcuimB12Block;
import net.pokefood.block.CalcuimB11Block;
import net.pokefood.block.CalcuimB10Block;
import net.pokefood.block.CalcuimB0Block;
import net.pokefood.block.BrandyBlock;
import net.pokefood.block.BlackTeaPlantBlock;
import net.pokefood.block.BlackTeaBlock;
import net.pokefood.block.BigOvenBlock;
import net.pokefood.block.BigBagBlock;
import net.pokefood.block.BeerBlock;
import net.pokefood.block.Barstool9Block;
import net.pokefood.block.Barstool8Block;
import net.pokefood.block.Barstool7Block;
import net.pokefood.block.Barstool6Block;
import net.pokefood.block.Barstool5Block;
import net.pokefood.block.Barstool4Block;
import net.pokefood.block.Barstool3Block;
import net.pokefood.block.Barstool2Block;
import net.pokefood.block.Barstool1Block;
import net.pokefood.block.Barstool15Block;
import net.pokefood.block.Barstool14Block;
import net.pokefood.block.Barstool13Block;
import net.pokefood.block.Barstool12Block;
import net.pokefood.block.Barstool11Block;
import net.pokefood.block.Barstool10Block;
import net.pokefood.block.Barstool0Block;
import net.pokefood.block.BananaWoodTreeControlerBlock;
import net.pokefood.block.BananaWoodStrippedBlock;
import net.pokefood.block.BananaWoodBlock;
import net.pokefood.block.BananaUnripedBlock;
import net.pokefood.block.BananaTrapdoorBlock;
import net.pokefood.block.BananaTopStrippedBlock;
import net.pokefood.block.BananaTopBlock;
import net.pokefood.block.BananaTeaBeerBlock;
import net.pokefood.block.BananaStairsBlock;
import net.pokefood.block.BananaSlabBlock;
import net.pokefood.block.BananaRipedBlock;
import net.pokefood.block.BananaPressurePlateBlock;
import net.pokefood.block.BananaPlantBlock;
import net.pokefood.block.BananaPlanksBlock;
import net.pokefood.block.BananaLogStrippedBlock;
import net.pokefood.block.BananaLogBlock;
import net.pokefood.block.BananaLog3StrippedBlock;
import net.pokefood.block.BananaLog3Block;
import net.pokefood.block.BananaLog2StrippedBlock;
import net.pokefood.block.BananaLog2ControlerBlock;
import net.pokefood.block.BananaLog2Block;
import net.pokefood.block.BananaLeavesBlock;
import net.pokefood.block.BananaFenceGateBlock;
import net.pokefood.block.BananaFenceBlock;
import net.pokefood.block.BananaDoorBlock;
import net.pokefood.block.BananaButtonBlock;
import net.pokefood.block.ArceumBlock;
import net.pokefood.block.ApricornBoxYBlock;
import net.pokefood.block.ApricornBoxWBlock;
import net.pokefood.block.ApricornBoxRBlock;
import net.pokefood.block.ApricornBoxPBlock;
import net.pokefood.block.ApricornBoxGBlock;
import net.pokefood.block.ApricornBoxDBlock;
import net.pokefood.block.ApricornBoxBBlock;
import net.pokefood.block.ApriJuiceYBlock;
import net.pokefood.block.ApriJuiceWBlock;
import net.pokefood.block.ApriJuiceRBlock;
import net.pokefood.block.ApriJuicePBlock;
import net.pokefood.block.ApriJuiceGBlock;
import net.pokefood.block.ApriJuiceDBlock;
import net.pokefood.block.ApriJuiceBBlock;
import net.pokefood.block.ApriAlcoholYBlock;
import net.pokefood.block.ApriAlcoholWBlock;
import net.pokefood.block.ApriAlcoholRBlock;
import net.pokefood.block.ApriAlcoholPBlock;
import net.pokefood.block.ApriAlcoholGBlock;
import net.pokefood.block.ApriAlcoholDBlock;
import net.pokefood.block.ApriAlcoholBBlock;
import net.pokefood.PokefoodMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class PokefoodModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PokefoodMod.MODID);
	public static final RegistryObject<Block> CHEESE_FULL_0 = REGISTRY.register("cheese_full_0", () -> new CheeseFull0Block());
	public static final RegistryObject<Block> CHEESE_FULL_1 = REGISTRY.register("cheese_full_1", () -> new CheeseFull1Block());
	public static final RegistryObject<Block> CHEESE_FULL_2 = REGISTRY.register("cheese_full_2", () -> new CheeseFull2Block());
	public static final RegistryObject<Block> CHEESE_FULL_3 = REGISTRY.register("cheese_full_3", () -> new CheeseFull3Block());
	public static final RegistryObject<Block> CHEESE_FULL_4 = REGISTRY.register("cheese_full_4", () -> new CheeseFull4Block());
	public static final RegistryObject<Block> CHEESE_FULL_5 = REGISTRY.register("cheese_full_5", () -> new CheeseFull5Block());
	public static final RegistryObject<Block> TEA = REGISTRY.register("tea", () -> new TeaBlock());
	public static final RegistryObject<Block> BLACK_TEA = REGISTRY.register("black_tea", () -> new BlackTeaBlock());
	public static final RegistryObject<Block> ROSERADE_TEA = REGISTRY.register("roserade_tea", () -> new RoseradeTeaBlock());
	public static final RegistryObject<Block> COFFEE = REGISTRY.register("coffee", () -> new CoffeeBlock());
	public static final RegistryObject<Block> COFFEE_ICED = REGISTRY.register("coffee_iced", () -> new CoffeeIcedBlock());
	public static final RegistryObject<Block> LATTE = REGISTRY.register("latte", () -> new LatteBlock());
	public static final RegistryObject<Block> LEMONADE = REGISTRY.register("lemonade", () -> new LemonadeBlock());
	public static final RegistryObject<Block> FRESH_WATER = REGISTRY.register("fresh_water", () -> new FreshWaterBlock());
	public static final RegistryObject<Block> CHERRY_INFUSION = REGISTRY.register("cherry_infusion", () -> new CherryInfusionBlock());
	public static final RegistryObject<Block> APRIJUICE_D = REGISTRY.register("aprijuice_d", () -> new ApriJuiceDBlock());
	public static final RegistryObject<Block> APRIJUICE_B = REGISTRY.register("aprijuice_b", () -> new ApriJuiceBBlock());
	public static final RegistryObject<Block> APRIJUICE_G = REGISTRY.register("aprijuice_g", () -> new ApriJuiceGBlock());
	public static final RegistryObject<Block> APRIJUICE_Y = REGISTRY.register("aprijuice_y", () -> new ApriJuiceYBlock());
	public static final RegistryObject<Block> APRIJUICE_R = REGISTRY.register("aprijuice_r", () -> new ApriJuiceRBlock());
	public static final RegistryObject<Block> APRIJUICE_P = REGISTRY.register("aprijuice_p", () -> new ApriJuicePBlock());
	public static final RegistryObject<Block> APRIJUICE_W = REGISTRY.register("aprijuice_w", () -> new ApriJuiceWBlock());
	public static final RegistryObject<Block> GRAPE_SPROUT = REGISTRY.register("grape_sprout", () -> new GrapeSproutBlock());
	public static final RegistryObject<Block> COOKING_POT = REGISTRY.register("cooking_pot", () -> new CookingPotBlock());
	public static final RegistryObject<Block> CARBONIZER = REGISTRY.register("carbonizer", () -> new CarbonizerBottleBlock());
	public static final RegistryObject<Block> OVEN = REGISTRY.register("oven", () -> new BigOvenBlock());
	public static final RegistryObject<Block> MIXER_RED = REGISTRY.register("mixer_red", () -> new MixerRedBlock());
	public static final RegistryObject<Block> MIXER_PINK = REGISTRY.register("mixer_pink", () -> new MixerPinkBlock());
	public static final RegistryObject<Block> MIXER_YELLOW = REGISTRY.register("mixer_yellow", () -> new MixerYellowBlock());
	public static final RegistryObject<Block> MIXER_GREEN = REGISTRY.register("mixer_green", () -> new MixerGreenBlock());
	public static final RegistryObject<Block> MIXER_BLUE = REGISTRY.register("mixer_blue", () -> new MixerBlueBlock());
	public static final RegistryObject<Block> KEG = REGISTRY.register("keg", () -> new KegBlock());
	public static final RegistryObject<Block> KEG_FUNNEL = REGISTRY.register("keg_funnel", () -> new KegFunnelBlock());
	public static final RegistryObject<Block> FRYER = REGISTRY.register("fryer", () -> new FryerBlock());
	public static final RegistryObject<Block> ICE_CREAM_MAKER = REGISTRY.register("ice_cream_maker", () -> new IceCreamMakerBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION = REGISTRY.register("ice_cream_extention", () -> new IceCreamExtentionBlock());
	public static final RegistryObject<Block> COFFEE_MAKER = REGISTRY.register("coffee_maker", () -> new CoffeeMakerBlock());
	public static final RegistryObject<Block> CURRY_POT = REGISTRY.register("curry_pot", () -> new CurryPotBlock());
	public static final RegistryObject<Block> CHEESE_MOLD = REGISTRY.register("cheese_mold", () -> new CheeseMoldBlock());
	public static final RegistryObject<Block> CREPE_MAKER = REGISTRY.register("crepe_maker", () -> new CrepeMakerBlock());
	public static final RegistryObject<Block> SUGAR_MELTER_0 = REGISTRY.register("sugar_melter_0", () -> new SugarMelter0Block());
	public static final RegistryObject<Block> SUGAR_MELTER_1 = REGISTRY.register("sugar_melter_1", () -> new SugarMelter1Block());
	public static final RegistryObject<Block> SUGAR_MELTER_2 = REGISTRY.register("sugar_melter_2", () -> new SugarMelter2Block());
	public static final RegistryObject<Block> SUGAR_MELTER_4 = REGISTRY.register("sugar_melter_4", () -> new SugarMelter4Block());
	public static final RegistryObject<Block> SUGAR_MELTER_5 = REGISTRY.register("sugar_melter_5", () -> new SugarMelter5Block());
	public static final RegistryObject<Block> SUGAR_MELTER_6 = REGISTRY.register("sugar_melter_6", () -> new SugarMelter6Block());
	public static final RegistryObject<Block> SUGAR_MELTER_3 = REGISTRY.register("sugar_melter_3", () -> new SugarMelter3Block());
	public static final RegistryObject<Block> SUGAR_MELTER_7 = REGISTRY.register("sugar_melter_7", () -> new SugarMelter7Block());
	public static final RegistryObject<Block> SUGAR_MELTER_8 = REGISTRY.register("sugar_melter_8", () -> new SugarMelter8Block());
	public static final RegistryObject<Block> SUGAR_MELTER_9 = REGISTRY.register("sugar_melter_9", () -> new SugarMelter9Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_0 = REGISTRY.register("mortar_and_pestle_0", () -> new MortarAndPestle0Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_1 = REGISTRY.register("mortar_and_pestle_1", () -> new MortarAndPestle1Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_2 = REGISTRY.register("mortar_and_pestle_2", () -> new MortarAndPestle2Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_3 = REGISTRY.register("mortar_and_pestle_3", () -> new MortarAndPestle3Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_4 = REGISTRY.register("mortar_and_pestle_4", () -> new MortarAndPestle4Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_5 = REGISTRY.register("mortar_and_pestle_5", () -> new MortarAndPestle5Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_6 = REGISTRY.register("mortar_and_pestle_6", () -> new MortarAndPestle6Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_7 = REGISTRY.register("mortar_and_pestle_7", () -> new MortarAndPestle7Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_9 = REGISTRY.register("mortar_and_pestle_9", () -> new MortarAndPestle9Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_8 = REGISTRY.register("mortar_and_pestle_8", () -> new MortarAndPestle8Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_10 = REGISTRY.register("mortar_and_pestle_10", () -> new MortarAndPestle10Block());
	public static final RegistryObject<Block> MORTAR_AND_PESTLE_11 = REGISTRY.register("mortar_and_pestle_11", () -> new MortarAndPestle11Block());
	public static final RegistryObject<Block> HEATER = REGISTRY.register("heater", () -> new HeaterBlock());
	public static final RegistryObject<Block> COOLER_BLUE = REGISTRY.register("cooler_blue", () -> new CoolerBlueBlock());
	public static final RegistryObject<Block> COOLER_GREEN = REGISTRY.register("cooler_green", () -> new CoolerGreenBlock());
	public static final RegistryObject<Block> COOLER_YELLOW = REGISTRY.register("cooler_yellow", () -> new CoolerYellowBlock());
	public static final RegistryObject<Block> COOLER_PINK = REGISTRY.register("cooler_pink", () -> new CoolerPinkBlock());
	public static final RegistryObject<Block> COOLER_RED = REGISTRY.register("cooler_red", () -> new CoolerRedBlock());
	public static final RegistryObject<Block> DISPLAY_CASE_EMPTY = REGISTRY.register("display_case_empty", () -> new DisplayCaseEmptyBlock());
	public static final RegistryObject<Block> CONE_DISPLAY = REGISTRY.register("cone_display", () -> new ConeDisplayBlock());
	public static final RegistryObject<Block> BIG_BAG = REGISTRY.register("big_bag", () -> new BigBagBlock());
	public static final RegistryObject<Block> PACK_EMPTY = REGISTRY.register("pack_empty", () -> new PackEmptyBlock());
	public static final RegistryObject<Block> PACK_APRI_D = REGISTRY.register("pack_apri_d", () -> new PackApriDBlock());
	public static final RegistryObject<Block> PACK_APRI_B = REGISTRY.register("pack_apri_b", () -> new PackApriBBlock());
	public static final RegistryObject<Block> PACK_APRI_G = REGISTRY.register("pack_apri_g", () -> new PackApriGBlock());
	public static final RegistryObject<Block> PACK_APRI_Y = REGISTRY.register("pack_apri_y", () -> new PackApriYBlock());
	public static final RegistryObject<Block> PACK_APRI_R = REGISTRY.register("pack_apri_r", () -> new PackApriRBlock());
	public static final RegistryObject<Block> PACK_APRI_P = REGISTRY.register("pack_apri_p", () -> new PackApriPBlock());
	public static final RegistryObject<Block> PACK_APRI_W = REGISTRY.register("pack_apri_w", () -> new PackApriWBlock());
	public static final RegistryObject<Block> PACK_TEA = REGISTRY.register("pack_tea", () -> new PackTeaBlock());
	public static final RegistryObject<Block> PACK_TEA_BLACK = REGISTRY.register("pack_tea_black", () -> new PackTeaBlackBlock());
	public static final RegistryObject<Block> PACK_TEA_ROSERADE = REGISTRY.register("pack_tea_roserade", () -> new PackTeaRoseradeBlock());
	public static final RegistryObject<Block> PACK_CHERRY = REGISTRY.register("pack_cherry", () -> new PackCherryBlock());
	public static final RegistryObject<Block> PACK_LEMONADE = REGISTRY.register("pack_lemonade", () -> new PackLemonadeBlock());
	public static final RegistryObject<Block> PACK_POP = REGISTRY.register("pack_pop", () -> new PackPopBlock());
	public static final RegistryObject<Block> PACK_COFFEE = REGISTRY.register("pack_coffee", () -> new PackCoffeeBlock());
	public static final RegistryObject<Block> PACK_LATTE = REGISTRY.register("pack_latte", () -> new PackLatteBlock());
	public static final RegistryObject<Block> MALT = REGISTRY.register("malt", () -> new MaltBlock());
	public static final RegistryObject<Block> BEER = REGISTRY.register("beer", () -> new BeerBlock());
	public static final RegistryObject<Block> BANANA_TEA_BEER = REGISTRY.register("banana_tea_beer", () -> new BananaTeaBeerBlock());
	public static final RegistryObject<Block> CHERRY_CALCUIM_BEER = REGISTRY.register("cherry_calcuim_beer", () -> new CherryCalcuimBeerBlock());
	public static final RegistryObject<Block> BRANDY = REGISTRY.register("brandy", () -> new BrandyBlock());
	public static final RegistryObject<Block> CIDRONADE = REGISTRY.register("cidronade", () -> new CidronadeBlock());
	public static final RegistryObject<Block> ARCEUM = REGISTRY.register("arceum", () -> new ArceumBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_D = REGISTRY.register("apri_alcohol_d", () -> new ApriAlcoholDBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_B = REGISTRY.register("apri_alcohol_b", () -> new ApriAlcoholBBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_G = REGISTRY.register("apri_alcohol_g", () -> new ApriAlcoholGBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_Y = REGISTRY.register("apri_alcohol_y", () -> new ApriAlcoholYBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_R = REGISTRY.register("apri_alcohol_r", () -> new ApriAlcoholRBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_P = REGISTRY.register("apri_alcohol_p", () -> new ApriAlcoholPBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_W = REGISTRY.register("apri_alcohol_w", () -> new ApriAlcoholWBlock());
	public static final RegistryObject<Block> RED_WINE = REGISTRY.register("red_wine", () -> new RedWineBlock());
	public static final RegistryObject<Block> WHITE_WINE = REGISTRY.register("white_wine", () -> new WhiteWineBlock());
	public static final RegistryObject<Block> ROSE_WINE = REGISTRY.register("rose_wine", () -> new RoseWineBlock());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_0 = REGISTRY.register("crystalized_sugar_block_0", () -> new CrystalizedSugarBlock0Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_1 = REGISTRY.register("crystalized_sugar_block_1", () -> new CrystalizedSugarBlock1Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_2 = REGISTRY.register("crystalized_sugar_block_2", () -> new CrystalizedSugarBlock2Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_3 = REGISTRY.register("crystalized_sugar_block_3", () -> new CrystalizedSugarBlock3Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_4 = REGISTRY.register("crystalized_sugar_block_4", () -> new CrystalizedSugarBlock4Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_5 = REGISTRY.register("crystalized_sugar_block_5", () -> new CrystalizedSugarBlock5Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_6 = REGISTRY.register("crystalized_sugar_block_6", () -> new CrystalizedSugarBlock6Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_7 = REGISTRY.register("crystalized_sugar_block_7", () -> new CrystalizedSugarBlock7Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_9 = REGISTRY.register("crystalized_sugar_block_9", () -> new CrystalizedSugarBlock9Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_8 = REGISTRY.register("crystalized_sugar_block_8", () -> new CrystalizedSugarBlock8Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_10 = REGISTRY.register("crystalized_sugar_block_10", () -> new CrystalizedSugarBlock10Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_11 = REGISTRY.register("crystalized_sugar_block_11", () -> new CrystalizedSugarBlock11Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_12 = REGISTRY.register("crystalized_sugar_block_12", () -> new CrystalizedSugarBlock12Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_13 = REGISTRY.register("crystalized_sugar_block_13", () -> new CrystalizedSugarBlock13Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_14 = REGISTRY.register("crystalized_sugar_block_14", () -> new CrystalizedSugarBlock14Block());
	public static final RegistryObject<Block> CRYSTALIZED_SUGAR_BLOCK_15 = REGISTRY.register("crystalized_sugar_block_15", () -> new CrystalizedSugarBlock15Block());
	public static final RegistryObject<Block> CHAIR_0 = REGISTRY.register("chair_0", () -> new Chair0Block());
	public static final RegistryObject<Block> CHAIR_1 = REGISTRY.register("chair_1", () -> new Chair1Block());
	public static final RegistryObject<Block> COFFEE_TABLE_0 = REGISTRY.register("coffee_table_0", () -> new CoffeeTable0Block());
	public static final RegistryObject<Block> COFFEE_TABLE_1 = REGISTRY.register("coffee_table_1", () -> new CoffeeTable1Block());
	public static final RegistryObject<Block> COFFEE_TABLE_2 = REGISTRY.register("coffee_table_2", () -> new CoffeeTable2Block());
	public static final RegistryObject<Block> COFFEE_TABLE_3 = REGISTRY.register("coffee_table_3", () -> new CoffeeTable3Block());
	public static final RegistryObject<Block> COFFEE_TABLE_4 = REGISTRY.register("coffee_table_4", () -> new CoffeeTable4Block());
	public static final RegistryObject<Block> COFFEE_TABLE_5 = REGISTRY.register("coffee_table_5", () -> new CoffeeTable5Block());
	public static final RegistryObject<Block> COFFEE_TABLE_6 = REGISTRY.register("coffee_table_6", () -> new CoffeeTable6Block());
	public static final RegistryObject<Block> COFFEE_TABLE_7 = REGISTRY.register("coffee_table_7", () -> new CoffeeTable7Block());
	public static final RegistryObject<Block> COFFEE_TABLE_8 = REGISTRY.register("coffee_table_8", () -> new CoffeeTable8Block());
	public static final RegistryObject<Block> COFFEE_TABLE_9 = REGISTRY.register("coffee_table_9", () -> new CoffeeTable9Block());
	public static final RegistryObject<Block> COFFEE_TABLE_10 = REGISTRY.register("coffee_table_10", () -> new CoffeeTable10Block());
	public static final RegistryObject<Block> COFFEE_TABLE_11 = REGISTRY.register("coffee_table_11", () -> new CoffeeTable11Block());
	public static final RegistryObject<Block> BARSTOOL_0 = REGISTRY.register("barstool_0", () -> new Barstool0Block());
	public static final RegistryObject<Block> BARSTOOL_1 = REGISTRY.register("barstool_1", () -> new Barstool1Block());
	public static final RegistryObject<Block> BARSTOOL_2 = REGISTRY.register("barstool_2", () -> new Barstool2Block());
	public static final RegistryObject<Block> BARSTOOL_3 = REGISTRY.register("barstool_3", () -> new Barstool3Block());
	public static final RegistryObject<Block> BARSTOOL_4 = REGISTRY.register("barstool_4", () -> new Barstool4Block());
	public static final RegistryObject<Block> BARSTOOL_6 = REGISTRY.register("barstool_6", () -> new Barstool6Block());
	public static final RegistryObject<Block> BARSTOOL_5 = REGISTRY.register("barstool_5", () -> new Barstool5Block());
	public static final RegistryObject<Block> BARSTOOL_7 = REGISTRY.register("barstool_7", () -> new Barstool7Block());
	public static final RegistryObject<Block> BARSTOOL_8 = REGISTRY.register("barstool_8", () -> new Barstool8Block());
	public static final RegistryObject<Block> BARSTOOL_9 = REGISTRY.register("barstool_9", () -> new Barstool9Block());
	public static final RegistryObject<Block> BARSTOOL_10 = REGISTRY.register("barstool_10", () -> new Barstool10Block());
	public static final RegistryObject<Block> BARSTOOL_11 = REGISTRY.register("barstool_11", () -> new Barstool11Block());
	public static final RegistryObject<Block> BARSTOOL_12 = REGISTRY.register("barstool_12", () -> new Barstool12Block());
	public static final RegistryObject<Block> BARSTOOL_13 = REGISTRY.register("barstool_13", () -> new Barstool13Block());
	public static final RegistryObject<Block> BARSTOOL_14 = REGISTRY.register("barstool_14", () -> new Barstool14Block());
	public static final RegistryObject<Block> BARSTOOL_15 = REGISTRY.register("barstool_15", () -> new Barstool15Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_0 = REGISTRY.register("restaurant_sofa_0", () -> new RestaurantSofa0Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_1 = REGISTRY.register("restaurant_sofa_1", () -> new RestaurantSofa1Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_2 = REGISTRY.register("restaurant_sofa_2", () -> new RestaurantSofa2Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_3 = REGISTRY.register("restaurant_sofa_3", () -> new RestaurantSofa3Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_4 = REGISTRY.register("restaurant_sofa_4", () -> new RestaurantSofa4Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_5 = REGISTRY.register("restaurant_sofa_5", () -> new RestaurantSofa5Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_6 = REGISTRY.register("restaurant_sofa_6", () -> new RestaurantSofa6Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_7 = REGISTRY.register("restaurant_sofa_7", () -> new RestaurantSofa7Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_8 = REGISTRY.register("restaurant_sofa_8", () -> new RestaurantSofa8Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_9 = REGISTRY.register("restaurant_sofa_9", () -> new RestaurantSofa9Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_10 = REGISTRY.register("restaurant_sofa_10", () -> new RestaurantSofa10Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_11 = REGISTRY.register("restaurant_sofa_11", () -> new RestaurantSofa11Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_12 = REGISTRY.register("restaurant_sofa_12", () -> new RestaurantSofa12Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_13 = REGISTRY.register("restaurant_sofa_13", () -> new RestaurantSofa13Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_14 = REGISTRY.register("restaurant_sofa_14", () -> new RestaurantSofa14Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_15 = REGISTRY.register("restaurant_sofa_15", () -> new RestaurantSofa15Block());
	public static final RegistryObject<Block> LAMP_0_OFF = REGISTRY.register("lamp_0_off", () -> new Lamp0OffBlock());
	public static final RegistryObject<Block> CANDY_MACHINE_0 = REGISTRY.register("candy_machine_0", () -> new CandyMachine0Block());
	public static final RegistryObject<Block> CANDY_MACHINE_1 = REGISTRY.register("candy_machine_1", () -> new CandyMachine1Block());
	public static final RegistryObject<Block> CANDY_MACHINE_2 = REGISTRY.register("candy_machine_2", () -> new CandyMachine2Block());
	public static final RegistryObject<Block> CANDY_MACHINE_3 = REGISTRY.register("candy_machine_3", () -> new CandyMachine3Block());
	public static final RegistryObject<Block> CANDY_MACHINE_4 = REGISTRY.register("candy_machine_4", () -> new CandyMachine4Block());
	public static final RegistryObject<Block> CANDY_MACHINE_5 = REGISTRY.register("candy_machine_5", () -> new CandyMachine5Block());
	public static final RegistryObject<Block> CANDY_MACHINE_7 = REGISTRY.register("candy_machine_7", () -> new CandyMachine7Block());
	public static final RegistryObject<Block> CANDY_MACHINE_6 = REGISTRY.register("candy_machine_6", () -> new CandyMachine6Block());
	public static final RegistryObject<Block> CANDY_MACHINE_8 = REGISTRY.register("candy_machine_8", () -> new CandyMachine8Block());
	public static final RegistryObject<Block> CANDY_MACHINE_9 = REGISTRY.register("candy_machine_9", () -> new CandyMachine9Block());
	public static final RegistryObject<Block> CANDY_MACHINE_10 = REGISTRY.register("candy_machine_10", () -> new CandyMachine10Block());
	public static final RegistryObject<Block> CANDY_MACHINE_11 = REGISTRY.register("candy_machine_11", () -> new CandyMachine11Block());
	public static final RegistryObject<Block> CANDY_MACHINE_12 = REGISTRY.register("candy_machine_12", () -> new CandyMachine12Block());
	public static final RegistryObject<Block> CANDY_MACHINE_13 = REGISTRY.register("candy_machine_13", () -> new CandyMachine13Block());
	public static final RegistryObject<Block> CANDY_MACHINE_14 = REGISTRY.register("candy_machine_14", () -> new CandyMachine14Block());
	public static final RegistryObject<Block> CANDY_MACHINE_15 = REGISTRY.register("candy_machine_15", () -> new CandyMachine15Block());
	public static final RegistryObject<Block> BANANA_WOOD = REGISTRY.register("banana_wood", () -> new BananaWoodBlock());
	public static final RegistryObject<Block> BANANA_LOG = REGISTRY.register("banana_log", () -> new BananaLogBlock());
	public static final RegistryObject<Block> BANANA_LOG_2 = REGISTRY.register("banana_log_2", () -> new BananaLog2Block());
	public static final RegistryObject<Block> BANANA_LOG_3 = REGISTRY.register("banana_log_3", () -> new BananaLog3Block());
	public static final RegistryObject<Block> BANANA_WOOD_STRIPPED = REGISTRY.register("banana_wood_stripped", () -> new BananaWoodStrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_STRIPPED = REGISTRY.register("banana_log_stripped", () -> new BananaLogStrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_2_STRIPPED = REGISTRY.register("banana_log_2_stripped", () -> new BananaLog2StrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_3_STRIPPED = REGISTRY.register("banana_log_3_stripped", () -> new BananaLog3StrippedBlock());
	public static final RegistryObject<Block> BANANA_PLANKS = REGISTRY.register("banana_planks", () -> new BananaPlanksBlock());
	public static final RegistryObject<Block> BANANA_STAIRS = REGISTRY.register("banana_stairs", () -> new BananaStairsBlock());
	public static final RegistryObject<Block> BANANA_SLAB = REGISTRY.register("banana_slab", () -> new BananaSlabBlock());
	public static final RegistryObject<Block> BANANA_FENCE = REGISTRY.register("banana_fence", () -> new BananaFenceBlock());
	public static final RegistryObject<Block> BANANA_BUTTON = REGISTRY.register("banana_button", () -> new BananaButtonBlock());
	public static final RegistryObject<Block> BANANA_PRESSURE_PLATE = REGISTRY.register("banana_pressure_plate", () -> new BananaPressurePlateBlock());
	public static final RegistryObject<Block> BANANA_DOOR = REGISTRY.register("banana_door", () -> new BananaDoorBlock());
	public static final RegistryObject<Block> BANANA_TRAPDOOR = REGISTRY.register("banana_trapdoor", () -> new BananaTrapdoorBlock());
	public static final RegistryObject<Block> BANANA_FENCE_GATE = REGISTRY.register("banana_fence_gate", () -> new BananaFenceGateBlock());
	public static final RegistryObject<Block> LEMON_STAGE_0 = REGISTRY.register("lemon_stage_0", () -> new LemonStage0Block());
	public static final RegistryObject<Block> LEMON_STAGE_1 = REGISTRY.register("lemon_stage_1", () -> new LemonStage1Block());
	public static final RegistryObject<Block> LEMON_STAGE_2 = REGISTRY.register("lemon_stage_2", () -> new LemonStage2Block());
	public static final RegistryObject<Block> LEMON_STAGE_3 = REGISTRY.register("lemon_stage_3", () -> new LemonStage3Block());
	public static final RegistryObject<Block> LEMON_STAGE_4 = REGISTRY.register("lemon_stage_4", () -> new LemonStage4Block());
	public static final RegistryObject<Block> LEMON_STAGE_5 = REGISTRY.register("lemon_stage_5", () -> new LemonStage5Block());
	public static final RegistryObject<Block> LEMON_STAGE_6 = REGISTRY.register("lemon_stage_6", () -> new LemonStage6Block());
	public static final RegistryObject<Block> COFFEE_MAKER_COOKING = REGISTRY.register("coffee_maker_cooking", () -> new CoffeeMakerCookingBlock());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_0 = REGISTRY.register("display_case_puffs_0", () -> new DisplayCasePuffs0Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_1 = REGISTRY.register("display_case_puffs_1", () -> new DisplayCasePuffs1Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_2 = REGISTRY.register("display_case_puffs_2", () -> new DisplayCasePuffs2Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_3 = REGISTRY.register("display_case_puffs_3", () -> new DisplayCasePuffs3Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_4 = REGISTRY.register("display_case_puffs_4", () -> new DisplayCasePuffs4Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_5 = REGISTRY.register("display_case_puffs_5", () -> new DisplayCasePuffs5Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_6 = REGISTRY.register("display_case_puffs_6", () -> new DisplayCasePuffs6Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_7 = REGISTRY.register("display_case_puffs_7", () -> new DisplayCasePuffs7Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_8 = REGISTRY.register("display_case_puffs_8", () -> new DisplayCasePuffs8Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_9 = REGISTRY.register("display_case_puffs_9", () -> new DisplayCasePuffs9Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_10 = REGISTRY.register("display_case_puffs_10", () -> new DisplayCasePuffs10Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_11 = REGISTRY.register("display_case_puffs_11", () -> new DisplayCasePuffs11Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_12 = REGISTRY.register("display_case_puffs_12", () -> new DisplayCasePuffs12Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_13 = REGISTRY.register("display_case_puffs_13", () -> new DisplayCasePuffs13Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_14 = REGISTRY.register("display_case_puffs_14", () -> new DisplayCasePuffs14Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_0 = REGISTRY.register("display_case_poffin_0", () -> new DisplayCasePoffin0Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_1 = REGISTRY.register("display_case_poffin_1", () -> new DisplayCasePoffin1Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_2 = REGISTRY.register("display_case_poffin_2", () -> new DisplayCasePoffin2Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_3 = REGISTRY.register("display_case_poffin_3", () -> new DisplayCasePoffin3Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_4 = REGISTRY.register("display_case_poffin_4", () -> new DisplayCasePoffin4Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_5 = REGISTRY.register("display_case_poffin_5", () -> new DisplayCasePoffin5Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_6 = REGISTRY.register("display_case_poffin_6", () -> new DisplayCasePoffin6Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_7 = REGISTRY.register("display_case_poffin_7", () -> new DisplayCasePoffin7Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_8 = REGISTRY.register("display_case_poffin_8", () -> new DisplayCasePoffin8Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_9 = REGISTRY.register("display_case_poffin_9", () -> new DisplayCasePoffin9Block());
	public static final RegistryObject<Block> CARDBOARD_BOX = REGISTRY.register("cardboard_box", () -> new CardboardBoxBlock());
	public static final RegistryObject<Block> BANANA_LEAVES = REGISTRY.register("banana_leaves", () -> new BananaLeavesBlock());
	public static final RegistryObject<Block> BANANA_TOP = REGISTRY.register("banana_top", () -> new BananaTopBlock());
	public static final RegistryObject<Block> BANANA_UNRIPED = REGISTRY.register("banana_unriped", () -> new BananaUnripedBlock());
	public static final RegistryObject<Block> BANANA_RIPED = REGISTRY.register("banana_riped", () -> new BananaRipedBlock());
	public static final RegistryObject<Block> BANANA_WOOD_TREE_CONTROLER = REGISTRY.register("banana_wood_tree_controler", () -> new BananaWoodTreeControlerBlock());
	public static final RegistryObject<Block> BANANA_LOG_2_CONTROLER = REGISTRY.register("banana_log_2_controler", () -> new BananaLog2ControlerBlock());
	public static final RegistryObject<Block> BANANA_PLANT = REGISTRY.register("banana_plant", () -> new BananaPlantBlock());
	public static final RegistryObject<Block> BANANA_TOP_STRIPPED = REGISTRY.register("banana_top_stripped", () -> new BananaTopStrippedBlock());
	public static final RegistryObject<Block> COFFEE_MAKER_COOKED = REGISTRY.register("coffee_maker_cooked", () -> new CoffeeMakerCookedBlock());
	public static final RegistryObject<Block> CANDY_BOX = REGISTRY.register("candy_box", () -> new CandyBoxBlock());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_0 = REGISTRY.register("calcuim_empty_b_0", () -> new CalcuimEmptyB0Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_1 = REGISTRY.register("calcuim_empty_b_1", () -> new CalcuimEmptyB1Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_2 = REGISTRY.register("calcuim_empty_b_2", () -> new CalcuimEmptyB2Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_3 = REGISTRY.register("calcuim_empty_b_3", () -> new CalcuimEmptyB3Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_4 = REGISTRY.register("calcuim_empty_b_4", () -> new CalcuimEmptyB4Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_5 = REGISTRY.register("calcuim_empty_b_5", () -> new CalcuimEmptyB5Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_6 = REGISTRY.register("calcuim_empty_b_6", () -> new CalcuimEmptyB6Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_7 = REGISTRY.register("calcuim_empty_b_7", () -> new CalcuimEmptyB7Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_8 = REGISTRY.register("calcuim_empty_b_8", () -> new CalcuimEmptyB8Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_9 = REGISTRY.register("calcuim_empty_b_9", () -> new CalcuimEmptyB9Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_10 = REGISTRY.register("calcuim_empty_b_10", () -> new CalcuimEmptyB10Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_11 = REGISTRY.register("calcuim_empty_b_11", () -> new CalcuimEmptyB11Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_12 = REGISTRY.register("calcuim_empty_b_12", () -> new CalcuimEmptyB12Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_13 = REGISTRY.register("calcuim_empty_b_13", () -> new CalcuimEmptyB13Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_14 = REGISTRY.register("calcuim_empty_b_14", () -> new CalcuimEmptyB14Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_15 = REGISTRY.register("calcuim_empty_b_15", () -> new CalcuimEmptyB15Block());
	public static final RegistryObject<Block> CALCUIM_B_0 = REGISTRY.register("calcuim_b_0", () -> new CalcuimB0Block());
	public static final RegistryObject<Block> CALCUIM_B_1 = REGISTRY.register("calcuim_b_1", () -> new CalcuimB1Block());
	public static final RegistryObject<Block> CALCUIM_B_2 = REGISTRY.register("calcuim_b_2", () -> new CalcuimB2Block());
	public static final RegistryObject<Block> CALCUIM_B_3 = REGISTRY.register("calcuim_b_3", () -> new CalcuimB3Block());
	public static final RegistryObject<Block> CALCUIM_B_4 = REGISTRY.register("calcuim_b_4", () -> new CalcuimB4Block());
	public static final RegistryObject<Block> CALCUIM_B_5 = REGISTRY.register("calcuim_b_5", () -> new CalcuimB5Block());
	public static final RegistryObject<Block> CALCUIM_B_6 = REGISTRY.register("calcuim_b_6", () -> new CalcuimB6Block());
	public static final RegistryObject<Block> CALCUIM_B_7 = REGISTRY.register("calcuim_b_7", () -> new CalcuimB7Block());
	public static final RegistryObject<Block> CALCUIM_B_8 = REGISTRY.register("calcuim_b_8", () -> new CalcuimB8Block());
	public static final RegistryObject<Block> CALCUIM_B_9 = REGISTRY.register("calcuim_b_9", () -> new CalcuimB9Block());
	public static final RegistryObject<Block> CALCUIM_B_10 = REGISTRY.register("calcuim_b_10", () -> new CalcuimB10Block());
	public static final RegistryObject<Block> CALCUIM_B_11 = REGISTRY.register("calcuim_b_11", () -> new CalcuimB11Block());
	public static final RegistryObject<Block> CALCUIM_B_12 = REGISTRY.register("calcuim_b_12", () -> new CalcuimB12Block());
	public static final RegistryObject<Block> CALCUIM_B_13 = REGISTRY.register("calcuim_b_13", () -> new CalcuimB13Block());
	public static final RegistryObject<Block> CALCUIM_B_14 = REGISTRY.register("calcuim_b_14", () -> new CalcuimB14Block());
	public static final RegistryObject<Block> CALCUIM_B_15 = REGISTRY.register("calcuim_b_15", () -> new CalcuimB15Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_0 = REGISTRY.register("restaurant_sofa_corner_0", () -> new RestaurantSofaCorner0Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_1 = REGISTRY.register("restaurant_sofa_corner_1", () -> new RestaurantSofaCorner1Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_2 = REGISTRY.register("restaurant_sofa_corner_2", () -> new RestaurantSofaCorner2Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_3 = REGISTRY.register("restaurant_sofa_corner_3", () -> new RestaurantSofaCorner3Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_4 = REGISTRY.register("restaurant_sofa_corner_4", () -> new RestaurantSofaCorner4Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_5 = REGISTRY.register("restaurant_sofa_corner_5", () -> new RestaurantSofaCorner5Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_6 = REGISTRY.register("restaurant_sofa_corner_6", () -> new RestaurantSofaCorner6Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_7 = REGISTRY.register("restaurant_sofa_corner_7", () -> new RestaurantSofaCorner7Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_8 = REGISTRY.register("restaurant_sofa_corner_8", () -> new RestaurantSofaCorner8Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_9 = REGISTRY.register("restaurant_sofa_corner_9", () -> new RestaurantSofaCorner9Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_10 = REGISTRY.register("restaurant_sofa_corner_10", () -> new RestaurantSofaCorner10Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_11 = REGISTRY.register("restaurant_sofa_corner_11", () -> new RestaurantSofaCorner11Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_12 = REGISTRY.register("restaurant_sofa_corner_12", () -> new RestaurantSofaCorner12Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_13 = REGISTRY.register("restaurant_sofa_corner_13", () -> new RestaurantSofaCorner13Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_14 = REGISTRY.register("restaurant_sofa_corner_14", () -> new RestaurantSofaCorner14Block());
	public static final RegistryObject<Block> RESTAURANT_SOFA_CORNER_15 = REGISTRY.register("restaurant_sofa_corner_15", () -> new RestaurantSofaCorner15Block());
	public static final RegistryObject<Block> CUP_BLOCK = REGISTRY.register("cup_block", () -> new CupBlockBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_D = REGISTRY.register("cup_block_apri_d", () -> new CupBlockApriDBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_B = REGISTRY.register("cup_block_apri_b", () -> new CupBlockApriBBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_G = REGISTRY.register("cup_block_apri_g", () -> new CupBlockApriGBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_Y = REGISTRY.register("cup_block_apri_y", () -> new CupBlockApriYBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_R = REGISTRY.register("cup_block_apri_r", () -> new CupBlockApriRBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_P = REGISTRY.register("cup_block_apri_p", () -> new CupBlockApriPBlock());
	public static final RegistryObject<Block> CUP_BLOCK_APRI_W = REGISTRY.register("cup_block_apri_w", () -> new CupBlockApriWBlock());
	public static final RegistryObject<Block> CUP_BLOCK_TEA = REGISTRY.register("cup_block_tea", () -> new CupBlockTeaBlock());
	public static final RegistryObject<Block> CUP_BLOCK_BLACK_TEA = REGISTRY.register("cup_block_black_tea", () -> new CupBlockBlackTeaBlock());
	public static final RegistryObject<Block> CUP_BLOCK_ROSERADE_TEA = REGISTRY.register("cup_block_roserade_tea", () -> new CupBlockRoseradeTeaBlock());
	public static final RegistryObject<Block> CUP_BLOCK_LEMONADE = REGISTRY.register("cup_block_lemonade", () -> new CupBlockLemonadeBlock());
	public static final RegistryObject<Block> CUP_BLOCK_FRESH_WATER = REGISTRY.register("cup_block_fresh_water", () -> new CupBlockFreshWaterBlock());
	public static final RegistryObject<Block> CUP_BLOCK_COFFEE = REGISTRY.register("cup_block_coffee", () -> new CupBlockCoffeeBlock());
	public static final RegistryObject<Block> CUP_BLOCK_COFFEE_ICED = REGISTRY.register("cup_block_coffee_iced", () -> new CupBlockCoffeeIcedBlock());
	public static final RegistryObject<Block> CUP_BLOCK_LATTE = REGISTRY.register("cup_block_latte", () -> new CupBlockLatteBlock());
	public static final RegistryObject<Block> CUP_BLOCK_CHERRY_INFUSION = REGISTRY.register("cup_block_cherry_infusion", () -> new CupBlockCherryInfusionBlock());
	public static final RegistryObject<Block> LAMP_0_ON = REGISTRY.register("lamp_0_on", () -> new Lamp0OnBlock());
	public static final RegistryObject<Block> CHEESE_TQ_0 = REGISTRY.register("cheese_tq_0", () -> new CheeseTQ0Block());
	public static final RegistryObject<Block> CHEESE_TQ_1 = REGISTRY.register("cheese_tq_1", () -> new CheeseTQ1Block());
	public static final RegistryObject<Block> CHEESE_TQ_2 = REGISTRY.register("cheese_tq_2", () -> new CheeseTQ2Block());
	public static final RegistryObject<Block> CHEESE_TQ_3 = REGISTRY.register("cheese_tq_3", () -> new CheeseTQ3Block());
	public static final RegistryObject<Block> CHEESE_TQ_4 = REGISTRY.register("cheese_tq_4", () -> new CheeseTQ4Block());
	public static final RegistryObject<Block> CHEESE_TQ_5 = REGISTRY.register("cheese_tq_5", () -> new CheeseTQ5Block());
	public static final RegistryObject<Block> CHEESE_H_0 = REGISTRY.register("cheese_h_0", () -> new CheeseH0Block());
	public static final RegistryObject<Block> CHEESE_H_1 = REGISTRY.register("cheese_h_1", () -> new CheeseH1Block());
	public static final RegistryObject<Block> CHEESE_H_2 = REGISTRY.register("cheese_h_2", () -> new CheeseH2Block());
	public static final RegistryObject<Block> CHEESE_H_3 = REGISTRY.register("cheese_h_3", () -> new CheeseH3Block());
	public static final RegistryObject<Block> CHEESE_H_4 = REGISTRY.register("cheese_h_4", () -> new CheeseH4Block());
	public static final RegistryObject<Block> CHEESE_H_5 = REGISTRY.register("cheese_h_5", () -> new CheeseH5Block());
	public static final RegistryObject<Block> CHEESE_Q_0 = REGISTRY.register("cheese_q_0", () -> new CheeseQ0Block());
	public static final RegistryObject<Block> CHEESE_Q_1 = REGISTRY.register("cheese_q_1", () -> new CheeseQ1Block());
	public static final RegistryObject<Block> CHEESE_Q_2 = REGISTRY.register("cheese_q_2", () -> new CheeseQ2Block());
	public static final RegistryObject<Block> CHEESE_Q_3 = REGISTRY.register("cheese_q_3", () -> new CheeseQ3Block());
	public static final RegistryObject<Block> CHEESE_Q_4 = REGISTRY.register("cheese_q_4", () -> new CheeseQ4Block());
	public static final RegistryObject<Block> CHEESE_Q_5 = REGISTRY.register("cheese_q_5", () -> new CheeseQ5Block());
	public static final RegistryObject<Block> LETTUCE_WILD = REGISTRY.register("lettuce_wild", () -> new LettuceWildBlock());
	public static final RegistryObject<Block> RICE_STAGE_0 = REGISTRY.register("rice_stage_0", () -> new RiceStage0Block());
	public static final RegistryObject<Block> RICE_STAGE_1 = REGISTRY.register("rice_stage_1", () -> new RiceStage1Block());
	public static final RegistryObject<Block> RICE_STAGE_2 = REGISTRY.register("rice_stage_2", () -> new RiceStage2Block());
	public static final RegistryObject<Block> RICE_STAGE_3 = REGISTRY.register("rice_stage_3", () -> new RiceStage3Block());
	public static final RegistryObject<Block> RICE_STAGE_4 = REGISTRY.register("rice_stage_4", () -> new RiceStage4Block());
	public static final RegistryObject<Block> RICE_STAGE_5 = REGISTRY.register("rice_stage_5", () -> new RiceStage5Block());
	public static final RegistryObject<Block> PLATE_BLOCK = REGISTRY.register("plate_block", () -> new PlateBlockBlock());
	public static final RegistryObject<Block> GRAPE_VINE_0 = REGISTRY.register("grape_vine_0", () -> new GrapeVine0Block());
	public static final RegistryObject<Block> GRAPE_VINE_1 = REGISTRY.register("grape_vine_1", () -> new GrapeVine1Block());
	public static final RegistryObject<Block> GRAPE_VINE_2 = REGISTRY.register("grape_vine_2", () -> new GrapeVine2Block());
	public static final RegistryObject<Block> GRAPE_SPROUT_1 = REGISTRY.register("grape_sprout_1", () -> new GrapeSprout1Block());
	public static final RegistryObject<Block> GRAPE_SPROUT_2 = REGISTRY.register("grape_sprout_2", () -> new GrapeSprout2Block());
	public static final RegistryObject<Block> CUP_UNCOOKED_BLOCK = REGISTRY.register("cup_uncooked_block", () -> new CupUncookedBlockBlock());
	public static final RegistryObject<Block> APRICORN_BOX_D = REGISTRY.register("apricorn_box_d", () -> new ApricornBoxDBlock());
	public static final RegistryObject<Block> APRICORN_BOX_B = REGISTRY.register("apricorn_box_b", () -> new ApricornBoxBBlock());
	public static final RegistryObject<Block> APRICORN_BOX_G = REGISTRY.register("apricorn_box_g", () -> new ApricornBoxGBlock());
	public static final RegistryObject<Block> APRICORN_BOX_Y = REGISTRY.register("apricorn_box_y", () -> new ApricornBoxYBlock());
	public static final RegistryObject<Block> APRICORN_BOX_R = REGISTRY.register("apricorn_box_r", () -> new ApricornBoxRBlock());
	public static final RegistryObject<Block> APRICORN_BOX_P = REGISTRY.register("apricorn_box_p", () -> new ApricornBoxPBlock());
	public static final RegistryObject<Block> APRICORN_BOX_W = REGISTRY.register("apricorn_box_w", () -> new ApricornBoxWBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_POP = REGISTRY.register("display_soda_pop", () -> new DisplaySodaPopBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK = REGISTRY.register("display_soda_tea_black", () -> new DisplaySodaTeaBlackBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA = REGISTRY.register("display_soda_tea", () -> new DisplaySodaTeaBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE = REGISTRY.register("display_soda_tea_roserade", () -> new DisplaySodaTeaRoseradeBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE = REGISTRY.register("display_soda_lemonade", () -> new DisplaySodaLemonadeBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D = REGISTRY.register("display_soda_apri_d", () -> new DisplaySodaApriDBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B = REGISTRY.register("display_soda_apri_b", () -> new DisplaySodaApriBBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G = REGISTRY.register("display_soda_apri_g", () -> new DisplaySodaApriGBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y = REGISTRY.register("display_soda_apri_y", () -> new DisplaySodaApriYBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R = REGISTRY.register("display_soda_apri_r", () -> new DisplaySodaApriRBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P = REGISTRY.register("display_soda_apri_p", () -> new DisplaySodaApriPBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W = REGISTRY.register("display_soda_apri_w", () -> new DisplaySodaApriWBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY = REGISTRY.register("display_soda_cherry", () -> new DisplaySodaCherryBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE = REGISTRY.register("display_soda_sombrine", () -> new DisplaySodaSombrineBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE = REGISTRY.register("display_soda_sombrade", () -> new DisplaySodaSombradeBlock());
	public static final RegistryObject<Block> BLACK_TEA_PLANT = REGISTRY.register("black_tea_plant", () -> new BlackTeaPlantBlock());
	public static final RegistryObject<Block> GREEN_TEA_PLANT = REGISTRY.register("green_tea_plant", () -> new GreenTeaPlantBlock());
	public static final RegistryObject<Block> CALCUIM_CROP = REGISTRY.register("calcuim_crop", () -> new CalcuimCropBlock());
	public static final RegistryObject<Block> LEEK_PLANT = REGISTRY.register("leek_plant", () -> new LeekPlantBlock());
	public static final RegistryObject<Block> ONION_PLANT = REGISTRY.register("onion_plant", () -> new OnionPlantBlock());
	public static final RegistryObject<Block> LETTUCE_PLANT = REGISTRY.register("lettuce_plant", () -> new LettucePlantBlock());
}
