
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.pokefood.init;

import net.pokefood.block.entity.TrayBlockBlockEntity;
import net.pokefood.block.entity.ToGoBagB8BlockEntity;
import net.pokefood.block.entity.ToGoBagB7BlockEntity;
import net.pokefood.block.entity.ToGoBagB6BlockEntity;
import net.pokefood.block.entity.ToGoBagB5BlockEntity;
import net.pokefood.block.entity.ToGoBagB4BlockEntity;
import net.pokefood.block.entity.ToGoBagB3BlockEntity;
import net.pokefood.block.entity.ToGoBagB2BlockEntity;
import net.pokefood.block.entity.ToGoBagB1BlockEntity;
import net.pokefood.block.entity.ToGoBagB0BlockEntity;
import net.pokefood.block.entity.SugarMelter9BlockEntity;
import net.pokefood.block.entity.SugarMelter8BlockEntity;
import net.pokefood.block.entity.SugarMelter7BlockEntity;
import net.pokefood.block.entity.SugarMelter6BlockEntity;
import net.pokefood.block.entity.SugarMelter5BlockEntity;
import net.pokefood.block.entity.SugarMelter4BlockEntity;
import net.pokefood.block.entity.SugarMelter3BlockEntity;
import net.pokefood.block.entity.SugarMelter2BlockEntity;
import net.pokefood.block.entity.SugarMelter1BlockEntity;
import net.pokefood.block.entity.SugarMelter0BlockEntity;
import net.pokefood.block.entity.RiceStage5BlockEntity;
import net.pokefood.block.entity.RiceStage4BlockEntity;
import net.pokefood.block.entity.RiceStage3BlockEntity;
import net.pokefood.block.entity.RiceStage2BlockEntity;
import net.pokefood.block.entity.RiceStage1BlockEntity;
import net.pokefood.block.entity.RiceStage0BlockEntity;
import net.pokefood.block.entity.PokeBowl7BlockEntity;
import net.pokefood.block.entity.PokeBowl6BlockEntity;
import net.pokefood.block.entity.PokeBowl5BlockEntity;
import net.pokefood.block.entity.PokeBowl4BlockEntity;
import net.pokefood.block.entity.PokeBowl3BlockEntity;
import net.pokefood.block.entity.PokeBowl2BlockEntity;
import net.pokefood.block.entity.PokeBowl1BlockEntity;
import net.pokefood.block.entity.PokeBowl0BlockEntity;
import net.pokefood.block.entity.OnionPlantBlockEntity;
import net.pokefood.block.entity.MixerYellowBlockEntity;
import net.pokefood.block.entity.MixerRedBlockEntity;
import net.pokefood.block.entity.MixerPinkBlockEntity;
import net.pokefood.block.entity.MixerGreenBlockEntity;
import net.pokefood.block.entity.MixerBlueBlockEntity;
import net.pokefood.block.entity.LettucePlantBlockEntity;
import net.pokefood.block.entity.LemonStage6BlockEntity;
import net.pokefood.block.entity.LemonStage5BlockEntity;
import net.pokefood.block.entity.LemonStage4BlockEntity;
import net.pokefood.block.entity.LemonStage3BlockEntity;
import net.pokefood.block.entity.LemonStage2BlockEntity;
import net.pokefood.block.entity.LemonStage1BlockEntity;
import net.pokefood.block.entity.LemonStage0BlockEntity;
import net.pokefood.block.entity.LeekPlantBlockEntity;
import net.pokefood.block.entity.KegFunnelBlockEntity;
import net.pokefood.block.entity.KegBlockEntity;
import net.pokefood.block.entity.IceCreamMakerBlockEntity;
import net.pokefood.block.entity.IceCreamExtentionBlockEntity;
import net.pokefood.block.entity.HeaterBlockEntity;
import net.pokefood.block.entity.GreenTeaPlantBlockEntity;
import net.pokefood.block.entity.GrapeVine2BlockEntity;
import net.pokefood.block.entity.GrapeVine1BlockEntity;
import net.pokefood.block.entity.GrapeVine0BlockEntity;
import net.pokefood.block.entity.GrapeSproutBlockEntity;
import net.pokefood.block.entity.GrapeSprout2BlockEntity;
import net.pokefood.block.entity.GrapeSprout1BlockEntity;
import net.pokefood.block.entity.FryerBlockEntity;
import net.pokefood.block.entity.ExteriorCoffeeBoardBlockEntity;
import net.pokefood.block.entity.CurryPotBlockEntity;
import net.pokefood.block.entity.CrepeMakerBlockEntity;
import net.pokefood.block.entity.CoolerYellowBlockEntity;
import net.pokefood.block.entity.CoolerRedBlockEntity;
import net.pokefood.block.entity.CoolerPinkBlockEntity;
import net.pokefood.block.entity.CoolerGreenBlockEntity;
import net.pokefood.block.entity.CoolerBlueBlockEntity;
import net.pokefood.block.entity.CookingPotBlockEntity;
import net.pokefood.block.entity.ConeDisplayBlockEntity;
import net.pokefood.block.entity.CoffeeMakerBlockEntity;
import net.pokefood.block.entity.CoffeeBoardTallBlockEntity;
import net.pokefood.block.entity.CoffeeBoardBlockEntity;
import net.pokefood.block.entity.CheeseMoldBlockEntity;
import net.pokefood.block.entity.CardboardBoxBlockEntity;
import net.pokefood.block.entity.CarbonizerBottleBlockEntity;
import net.pokefood.block.entity.CandyMachine9BlockEntity;
import net.pokefood.block.entity.CandyMachine8BlockEntity;
import net.pokefood.block.entity.CandyMachine7BlockEntity;
import net.pokefood.block.entity.CandyMachine6BlockEntity;
import net.pokefood.block.entity.CandyMachine5BlockEntity;
import net.pokefood.block.entity.CandyMachine4BlockEntity;
import net.pokefood.block.entity.CandyMachine3BlockEntity;
import net.pokefood.block.entity.CandyMachine2BlockEntity;
import net.pokefood.block.entity.CandyMachine1BlockEntity;
import net.pokefood.block.entity.CandyMachine15BlockEntity;
import net.pokefood.block.entity.CandyMachine14BlockEntity;
import net.pokefood.block.entity.CandyMachine13BlockEntity;
import net.pokefood.block.entity.CandyMachine12BlockEntity;
import net.pokefood.block.entity.CandyMachine11BlockEntity;
import net.pokefood.block.entity.CandyMachine10BlockEntity;
import net.pokefood.block.entity.CandyMachine0BlockEntity;
import net.pokefood.block.entity.CandyBoxBlockEntity;
import net.pokefood.block.entity.CalcuimCropBlockEntity;
import net.pokefood.block.entity.BlenderBlockEntity;
import net.pokefood.block.entity.BlackTeaPlantBlockEntity;
import net.pokefood.block.entity.BigOvenBlockEntity;
import net.pokefood.block.entity.BigBagBlockEntity;
import net.pokefood.block.entity.BananaWoodTreeControlerBlockEntity;
import net.pokefood.block.entity.BananaPlantBlockEntity;
import net.pokefood.block.entity.BananaLog2ControlerBlockEntity;
import net.pokefood.block.entity.ApricornBoxYBlockEntity;
import net.pokefood.block.entity.ApricornBoxWBlockEntity;
import net.pokefood.block.entity.ApricornBoxRBlockEntity;
import net.pokefood.block.entity.ApricornBoxPBlockEntity;
import net.pokefood.block.entity.ApricornBoxGBlockEntity;
import net.pokefood.block.entity.ApricornBoxDBlockEntity;
import net.pokefood.block.entity.ApricornBoxBBlockEntity;
import net.pokefood.PokefoodMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;

public class PokefoodModBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITY_TYPES, PokefoodMod.MODID);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_SPROUT = register("grape_sprout", PokefoodModBlocks.GRAPE_SPROUT, GrapeSproutBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOKING_POT = register("cooking_pot", PokefoodModBlocks.COOKING_POT, CookingPotBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CARBONIZER = register("carbonizer", PokefoodModBlocks.CARBONIZER, CarbonizerBottleBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> OVEN = register("oven", PokefoodModBlocks.OVEN, BigOvenBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> MIXER_RED = register("mixer_red", PokefoodModBlocks.MIXER_RED, MixerRedBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> MIXER_PINK = register("mixer_pink", PokefoodModBlocks.MIXER_PINK, MixerPinkBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> MIXER_YELLOW = register("mixer_yellow", PokefoodModBlocks.MIXER_YELLOW, MixerYellowBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> MIXER_GREEN = register("mixer_green", PokefoodModBlocks.MIXER_GREEN, MixerGreenBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> MIXER_BLUE = register("mixer_blue", PokefoodModBlocks.MIXER_BLUE, MixerBlueBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BLENDER = register("blender", PokefoodModBlocks.BLENDER, BlenderBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> KEG = register("keg", PokefoodModBlocks.KEG, KegBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> KEG_FUNNEL = register("keg_funnel", PokefoodModBlocks.KEG_FUNNEL, KegFunnelBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> FRYER = register("fryer", PokefoodModBlocks.FRYER, FryerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> ICE_CREAM_MAKER = register("ice_cream_maker", PokefoodModBlocks.ICE_CREAM_MAKER, IceCreamMakerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> ICE_CREAM_EXTENTION = register("ice_cream_extention", PokefoodModBlocks.ICE_CREAM_EXTENTION, IceCreamExtentionBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COFFEE_MAKER = register("coffee_maker", PokefoodModBlocks.COFFEE_MAKER, CoffeeMakerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CURRY_POT = register("curry_pot", PokefoodModBlocks.CURRY_POT, CurryPotBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CHEESE_MOLD = register("cheese_mold", PokefoodModBlocks.CHEESE_MOLD, CheeseMoldBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CREPE_MAKER = register("crepe_maker", PokefoodModBlocks.CREPE_MAKER, CrepeMakerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_0 = register("sugar_melter_0", PokefoodModBlocks.SUGAR_MELTER_0, SugarMelter0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_1 = register("sugar_melter_1", PokefoodModBlocks.SUGAR_MELTER_1, SugarMelter1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_2 = register("sugar_melter_2", PokefoodModBlocks.SUGAR_MELTER_2, SugarMelter2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_4 = register("sugar_melter_4", PokefoodModBlocks.SUGAR_MELTER_4, SugarMelter4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_5 = register("sugar_melter_5", PokefoodModBlocks.SUGAR_MELTER_5, SugarMelter5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_6 = register("sugar_melter_6", PokefoodModBlocks.SUGAR_MELTER_6, SugarMelter6BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_3 = register("sugar_melter_3", PokefoodModBlocks.SUGAR_MELTER_3, SugarMelter3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_7 = register("sugar_melter_7", PokefoodModBlocks.SUGAR_MELTER_7, SugarMelter7BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_8 = register("sugar_melter_8", PokefoodModBlocks.SUGAR_MELTER_8, SugarMelter8BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> SUGAR_MELTER_9 = register("sugar_melter_9", PokefoodModBlocks.SUGAR_MELTER_9, SugarMelter9BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> HEATER = register("heater", PokefoodModBlocks.HEATER, HeaterBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOLER_BLUE = register("cooler_blue", PokefoodModBlocks.COOLER_BLUE, CoolerBlueBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOLER_GREEN = register("cooler_green", PokefoodModBlocks.COOLER_GREEN, CoolerGreenBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOLER_YELLOW = register("cooler_yellow", PokefoodModBlocks.COOLER_YELLOW, CoolerYellowBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOLER_PINK = register("cooler_pink", PokefoodModBlocks.COOLER_PINK, CoolerPinkBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COOLER_RED = register("cooler_red", PokefoodModBlocks.COOLER_RED, CoolerRedBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CONE_DISPLAY = register("cone_display", PokefoodModBlocks.CONE_DISPLAY, ConeDisplayBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BIG_BAG = register("big_bag", PokefoodModBlocks.BIG_BAG, BigBagBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_0 = register("candy_machine_0", PokefoodModBlocks.CANDY_MACHINE_0, CandyMachine0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_1 = register("candy_machine_1", PokefoodModBlocks.CANDY_MACHINE_1, CandyMachine1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_2 = register("candy_machine_2", PokefoodModBlocks.CANDY_MACHINE_2, CandyMachine2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_3 = register("candy_machine_3", PokefoodModBlocks.CANDY_MACHINE_3, CandyMachine3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_4 = register("candy_machine_4", PokefoodModBlocks.CANDY_MACHINE_4, CandyMachine4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_5 = register("candy_machine_5", PokefoodModBlocks.CANDY_MACHINE_5, CandyMachine5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_6 = register("candy_machine_6", PokefoodModBlocks.CANDY_MACHINE_6, CandyMachine6BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_7 = register("candy_machine_7", PokefoodModBlocks.CANDY_MACHINE_7, CandyMachine7BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_8 = register("candy_machine_8", PokefoodModBlocks.CANDY_MACHINE_8, CandyMachine8BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_9 = register("candy_machine_9", PokefoodModBlocks.CANDY_MACHINE_9, CandyMachine9BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_10 = register("candy_machine_10", PokefoodModBlocks.CANDY_MACHINE_10, CandyMachine10BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_11 = register("candy_machine_11", PokefoodModBlocks.CANDY_MACHINE_11, CandyMachine11BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_12 = register("candy_machine_12", PokefoodModBlocks.CANDY_MACHINE_12, CandyMachine12BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_13 = register("candy_machine_13", PokefoodModBlocks.CANDY_MACHINE_13, CandyMachine13BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_14 = register("candy_machine_14", PokefoodModBlocks.CANDY_MACHINE_14, CandyMachine14BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_MACHINE_15 = register("candy_machine_15", PokefoodModBlocks.CANDY_MACHINE_15, CandyMachine15BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_0 = register("poke_bowl_0", PokefoodModBlocks.POKE_BOWL_0, PokeBowl0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_1 = register("poke_bowl_1", PokefoodModBlocks.POKE_BOWL_1, PokeBowl1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_2 = register("poke_bowl_2", PokefoodModBlocks.POKE_BOWL_2, PokeBowl2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_3 = register("poke_bowl_3", PokefoodModBlocks.POKE_BOWL_3, PokeBowl3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_4 = register("poke_bowl_4", PokefoodModBlocks.POKE_BOWL_4, PokeBowl4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_5 = register("poke_bowl_5", PokefoodModBlocks.POKE_BOWL_5, PokeBowl5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_6 = register("poke_bowl_6", PokefoodModBlocks.POKE_BOWL_6, PokeBowl6BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> POKE_BOWL_7 = register("poke_bowl_7", PokefoodModBlocks.POKE_BOWL_7, PokeBowl7BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COFFEE_BOARD = register("coffee_board", PokefoodModBlocks.COFFEE_BOARD, CoffeeBoardBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> COFFEE_BOARD_TALL = register("coffee_board_tall", PokefoodModBlocks.COFFEE_BOARD_TALL, CoffeeBoardTallBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> EXTERIOR_COFFEE_BOARD = register("exterior_coffee_board", PokefoodModBlocks.EXTERIOR_COFFEE_BOARD, ExteriorCoffeeBoardBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_0 = register("lemon_stage_0", PokefoodModBlocks.LEMON_STAGE_0, LemonStage0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_1 = register("lemon_stage_1", PokefoodModBlocks.LEMON_STAGE_1, LemonStage1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_2 = register("lemon_stage_2", PokefoodModBlocks.LEMON_STAGE_2, LemonStage2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_3 = register("lemon_stage_3", PokefoodModBlocks.LEMON_STAGE_3, LemonStage3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_4 = register("lemon_stage_4", PokefoodModBlocks.LEMON_STAGE_4, LemonStage4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_5 = register("lemon_stage_5", PokefoodModBlocks.LEMON_STAGE_5, LemonStage5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEMON_STAGE_6 = register("lemon_stage_6", PokefoodModBlocks.LEMON_STAGE_6, LemonStage6BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CARDBOARD_BOX = register("cardboard_box", PokefoodModBlocks.CARDBOARD_BOX, CardboardBoxBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BANANA_WOOD_TREE_CONTROLER = register("banana_wood_tree_controler", PokefoodModBlocks.BANANA_WOOD_TREE_CONTROLER, BananaWoodTreeControlerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BANANA_LOG_2_CONTROLER = register("banana_log_2_controler", PokefoodModBlocks.BANANA_LOG_2_CONTROLER, BananaLog2ControlerBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BANANA_PLANT = register("banana_plant", PokefoodModBlocks.BANANA_PLANT, BananaPlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CANDY_BOX = register("candy_box", PokefoodModBlocks.CANDY_BOX, CandyBoxBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_0 = register("rice_stage_0", PokefoodModBlocks.RICE_STAGE_0, RiceStage0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_1 = register("rice_stage_1", PokefoodModBlocks.RICE_STAGE_1, RiceStage1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_2 = register("rice_stage_2", PokefoodModBlocks.RICE_STAGE_2, RiceStage2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_3 = register("rice_stage_3", PokefoodModBlocks.RICE_STAGE_3, RiceStage3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_4 = register("rice_stage_4", PokefoodModBlocks.RICE_STAGE_4, RiceStage4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> RICE_STAGE_5 = register("rice_stage_5", PokefoodModBlocks.RICE_STAGE_5, RiceStage5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_VINE_0 = register("grape_vine_0", PokefoodModBlocks.GRAPE_VINE_0, GrapeVine0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_VINE_1 = register("grape_vine_1", PokefoodModBlocks.GRAPE_VINE_1, GrapeVine1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_VINE_2 = register("grape_vine_2", PokefoodModBlocks.GRAPE_VINE_2, GrapeVine2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_SPROUT_1 = register("grape_sprout_1", PokefoodModBlocks.GRAPE_SPROUT_1, GrapeSprout1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GRAPE_SPROUT_2 = register("grape_sprout_2", PokefoodModBlocks.GRAPE_SPROUT_2, GrapeSprout2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_D = register("apricorn_box_d", PokefoodModBlocks.APRICORN_BOX_D, ApricornBoxDBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_B = register("apricorn_box_b", PokefoodModBlocks.APRICORN_BOX_B, ApricornBoxBBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_G = register("apricorn_box_g", PokefoodModBlocks.APRICORN_BOX_G, ApricornBoxGBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_Y = register("apricorn_box_y", PokefoodModBlocks.APRICORN_BOX_Y, ApricornBoxYBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_R = register("apricorn_box_r", PokefoodModBlocks.APRICORN_BOX_R, ApricornBoxRBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_P = register("apricorn_box_p", PokefoodModBlocks.APRICORN_BOX_P, ApricornBoxPBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> APRICORN_BOX_W = register("apricorn_box_w", PokefoodModBlocks.APRICORN_BOX_W, ApricornBoxWBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> BLACK_TEA_PLANT = register("black_tea_plant", PokefoodModBlocks.BLACK_TEA_PLANT, BlackTeaPlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> GREEN_TEA_PLANT = register("green_tea_plant", PokefoodModBlocks.GREEN_TEA_PLANT, GreenTeaPlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> CALCUIM_CROP = register("calcuim_crop", PokefoodModBlocks.CALCUIM_CROP, CalcuimCropBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LEEK_PLANT = register("leek_plant", PokefoodModBlocks.LEEK_PLANT, LeekPlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> ONION_PLANT = register("onion_plant", PokefoodModBlocks.ONION_PLANT, OnionPlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> LETTUCE_PLANT = register("lettuce_plant", PokefoodModBlocks.LETTUCE_PLANT, LettucePlantBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TRAY_BLOCK = register("tray_block", PokefoodModBlocks.TRAY_BLOCK, TrayBlockBlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_0 = register("to_go_bag_b_0", PokefoodModBlocks.TO_GO_BAG_B_0, ToGoBagB0BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_1 = register("to_go_bag_b_1", PokefoodModBlocks.TO_GO_BAG_B_1, ToGoBagB1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_2 = register("to_go_bag_b_2", PokefoodModBlocks.TO_GO_BAG_B_2, ToGoBagB2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_3 = register("to_go_bag_b_3", PokefoodModBlocks.TO_GO_BAG_B_3, ToGoBagB3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_4 = register("to_go_bag_b_4", PokefoodModBlocks.TO_GO_BAG_B_4, ToGoBagB4BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_5 = register("to_go_bag_b_5", PokefoodModBlocks.TO_GO_BAG_B_5, ToGoBagB5BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_6 = register("to_go_bag_b_6", PokefoodModBlocks.TO_GO_BAG_B_6, ToGoBagB6BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_7 = register("to_go_bag_b_7", PokefoodModBlocks.TO_GO_BAG_B_7, ToGoBagB7BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> TO_GO_BAG_B_8 = register("to_go_bag_b_8", PokefoodModBlocks.TO_GO_BAG_B_8, ToGoBagB8BlockEntity::new);

	private static RegistryObject<BlockEntityType<?>> register(String registryname, RegistryObject<Block> block, BlockEntityType.BlockEntitySupplier<?> supplier) {
		return REGISTRY.register(registryname, () -> BlockEntityType.Builder.of(supplier, block.get()).build(null));
	}
}
