
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.pokefood.init;

import net.pokefood.block.TeaStage2Block;
import net.pokefood.block.TeaStage1Block;
import net.pokefood.block.TeaStage0Block;
import net.pokefood.block.TeaBlock;
import net.pokefood.block.RoseradeTeaBlock;
import net.pokefood.block.PotWaterSugarBlock;
import net.pokefood.block.PotWaterLemonBlock;
import net.pokefood.block.PotWaterFiredBlock;
import net.pokefood.block.PotWaterBlock;
import net.pokefood.block.PotTeaFiredBlock;
import net.pokefood.block.PotTeaCookedBlock;
import net.pokefood.block.PotTeaBlock;
import net.pokefood.block.PotRoseradeTeaFiredBlock;
import net.pokefood.block.PotRoseradeTeaCookedBlock;
import net.pokefood.block.PotRoseradeTeaBlock;
import net.pokefood.block.PotMaltFiredBlock;
import net.pokefood.block.PotMaltCookedBlock;
import net.pokefood.block.PotMaltBlock;
import net.pokefood.block.PotLemonadeCookedBlock;
import net.pokefood.block.PotLemonadeBlock;
import net.pokefood.block.PotFreshWaterBlock;
import net.pokefood.block.PotEmptyBlock;
import net.pokefood.block.PotCherryFiredBlock;
import net.pokefood.block.PotCherryCookedBlock;
import net.pokefood.block.PotCherryBlock;
import net.pokefood.block.PotBlackTeaFiredBlock;
import net.pokefood.block.PotBlackTeaCookedBlock;
import net.pokefood.block.PotBlackTeaBlock;
import net.pokefood.block.PackTeaRoseradeBlock;
import net.pokefood.block.PackTeaRoserade8Block;
import net.pokefood.block.PackTeaRoserade4Block;
import net.pokefood.block.PackTeaBlock;
import net.pokefood.block.PackTeaBlackBlock;
import net.pokefood.block.PackTeaBlack8Block;
import net.pokefood.block.PackTeaBlack4Block;
import net.pokefood.block.PackTea8Block;
import net.pokefood.block.PackTea4Block;
import net.pokefood.block.PackPopBlock;
import net.pokefood.block.PackPop8Block;
import net.pokefood.block.PackPop4Block;
import net.pokefood.block.PackLemonadeBlock;
import net.pokefood.block.PackLemonade8Block;
import net.pokefood.block.PackLemonade4Block;
import net.pokefood.block.PackLatteBlock;
import net.pokefood.block.PackLatte8Block;
import net.pokefood.block.PackLatte4Block;
import net.pokefood.block.PackEmptyBlock;
import net.pokefood.block.PackCoffeeBlock;
import net.pokefood.block.PackCoffee8Block;
import net.pokefood.block.PackCoffee4Block;
import net.pokefood.block.PackCherryBlock;
import net.pokefood.block.PackCherry8Block;
import net.pokefood.block.PackCherry4Block;
import net.pokefood.block.PackApriYBlock;
import net.pokefood.block.PackApriY8Block;
import net.pokefood.block.PackApriY4Block;
import net.pokefood.block.PackApriWBlock;
import net.pokefood.block.PackApriW8Block;
import net.pokefood.block.PackApriW4Block;
import net.pokefood.block.PackApriRBlock;
import net.pokefood.block.PackApriR8Block;
import net.pokefood.block.PackApriR4Block;
import net.pokefood.block.PackApriPBlock;
import net.pokefood.block.PackApriP8Block;
import net.pokefood.block.PackApriP4Block;
import net.pokefood.block.PackApriGBlock;
import net.pokefood.block.PackApriG8Block;
import net.pokefood.block.PackApriG4Block;
import net.pokefood.block.PackApriDBlock;
import net.pokefood.block.PackApriD8Block;
import net.pokefood.block.PackApriD4Block;
import net.pokefood.block.PackApriBBlock;
import net.pokefood.block.PackApriB8Block;
import net.pokefood.block.PackApriB4Block;
import net.pokefood.block.MixerYellowBlock;
import net.pokefood.block.MixerRedBlock;
import net.pokefood.block.MixerPinkBlock;
import net.pokefood.block.MixerGreenBlock;
import net.pokefood.block.MixerBlueBlock;
import net.pokefood.block.MaltBlock;
import net.pokefood.block.LemonadeBlock;
import net.pokefood.block.LemonStage6Block;
import net.pokefood.block.LemonStage5Block;
import net.pokefood.block.LemonStage4Block;
import net.pokefood.block.LemonStage3Block;
import net.pokefood.block.LemonStage2Block;
import net.pokefood.block.LemonStage1Block;
import net.pokefood.block.LemonStage0Block;
import net.pokefood.block.LeekStage3Block;
import net.pokefood.block.LeekStage2Block;
import net.pokefood.block.LeekStage1Block;
import net.pokefood.block.LeekStage0Block;
import net.pokefood.block.LatteBlock;
import net.pokefood.block.KegFunnelUpBlock;
import net.pokefood.block.KegFunnelFrontBlock;
import net.pokefood.block.KegFunnelBlock;
import net.pokefood.block.KegBlock;
import net.pokefood.block.Keg7Block;
import net.pokefood.block.Keg6Block;
import net.pokefood.block.Keg5Block;
import net.pokefood.block.Keg4Block;
import net.pokefood.block.Keg3Block;
import net.pokefood.block.Keg2Block;
import net.pokefood.block.IceCreamMakerBlock;
import net.pokefood.block.IceCreamExtentionTeaRBlock;
import net.pokefood.block.IceCreamExtentionTeaBlock;
import net.pokefood.block.IceCreamExtentionTeaBBlock;
import net.pokefood.block.IceCreamExtentionLemonadeBlock;
import net.pokefood.block.IceCreamExtentionBlock;
import net.pokefood.block.IceCreamExtentionApriYBlock;
import net.pokefood.block.IceCreamExtentionApriWBlock;
import net.pokefood.block.IceCreamExtentionApriRBlock;
import net.pokefood.block.IceCreamExtentionApriPBlock;
import net.pokefood.block.IceCreamExtentionApriGBlock;
import net.pokefood.block.IceCreamExtentionApriDBlock;
import net.pokefood.block.IceCreamExtentionApriBBlock;
import net.pokefood.block.HeaterBlock;
import net.pokefood.block.FryerBlock;
import net.pokefood.block.FreshWaterBlock;
import net.pokefood.block.DisplaySodaTeaRoserade7Block;
import net.pokefood.block.DisplaySodaTeaRoserade6Block;
import net.pokefood.block.DisplaySodaTeaRoserade5Block;
import net.pokefood.block.DisplaySodaTeaRoserade4Block;
import net.pokefood.block.DisplaySodaTeaRoserade3Block;
import net.pokefood.block.DisplaySodaTeaRoserade2Block;
import net.pokefood.block.DisplaySodaTeaRoserade1Block;
import net.pokefood.block.DisplaySodaTeaBlack7Block;
import net.pokefood.block.DisplaySodaTeaBlack6Block;
import net.pokefood.block.DisplaySodaTeaBlack5Block;
import net.pokefood.block.DisplaySodaTeaBlack4Block;
import net.pokefood.block.DisplaySodaTeaBlack3Block;
import net.pokefood.block.DisplaySodaTeaBlack2Block;
import net.pokefood.block.DisplaySodaTeaBlack1Block;
import net.pokefood.block.DisplaySodaTea7Block;
import net.pokefood.block.DisplaySodaTea6Block;
import net.pokefood.block.DisplaySodaTea5Block;
import net.pokefood.block.DisplaySodaTea4Block;
import net.pokefood.block.DisplaySodaTea3Block;
import net.pokefood.block.DisplaySodaTea2Block;
import net.pokefood.block.DisplaySodaTea1Block;
import net.pokefood.block.DisplaySodaSombrine7Block;
import net.pokefood.block.DisplaySodaSombrine6Block;
import net.pokefood.block.DisplaySodaSombrine5Block;
import net.pokefood.block.DisplaySodaSombrine4Block;
import net.pokefood.block.DisplaySodaSombrine3Block;
import net.pokefood.block.DisplaySodaSombrine2Block;
import net.pokefood.block.DisplaySodaSombrine1Block;
import net.pokefood.block.DisplaySodaSombrade7Block;
import net.pokefood.block.DisplaySodaSombrade6Block;
import net.pokefood.block.DisplaySodaSombrade5Block;
import net.pokefood.block.DisplaySodaSombrade4Block;
import net.pokefood.block.DisplaySodaSombrade3Block;
import net.pokefood.block.DisplaySodaSombrade2Block;
import net.pokefood.block.DisplaySodaSombrade1Block;
import net.pokefood.block.DisplaySodaPop7Block;
import net.pokefood.block.DisplaySodaPop6Block;
import net.pokefood.block.DisplaySodaPop5Block;
import net.pokefood.block.DisplaySodaPop4Block;
import net.pokefood.block.DisplaySodaPop3Block;
import net.pokefood.block.DisplaySodaPop2Block;
import net.pokefood.block.DisplaySodaPop1Block;
import net.pokefood.block.DisplaySodaLemonade7Block;
import net.pokefood.block.DisplaySodaLemonade6Block;
import net.pokefood.block.DisplaySodaLemonade5Block;
import net.pokefood.block.DisplaySodaLemonade4Block;
import net.pokefood.block.DisplaySodaLemonade3Block;
import net.pokefood.block.DisplaySodaLemonade2Block;
import net.pokefood.block.DisplaySodaLemonade1Block;
import net.pokefood.block.DisplaySodaCherry7Block;
import net.pokefood.block.DisplaySodaCherry6Block;
import net.pokefood.block.DisplaySodaCherry5Block;
import net.pokefood.block.DisplaySodaCherry4Block;
import net.pokefood.block.DisplaySodaCherry3Block;
import net.pokefood.block.DisplaySodaCherry2Block;
import net.pokefood.block.DisplaySodaCherry1Block;
import net.pokefood.block.DisplaySodaApriY7Block;
import net.pokefood.block.DisplaySodaApriY6Block;
import net.pokefood.block.DisplaySodaApriY5Block;
import net.pokefood.block.DisplaySodaApriY4Block;
import net.pokefood.block.DisplaySodaApriY3Block;
import net.pokefood.block.DisplaySodaApriY2Block;
import net.pokefood.block.DisplaySodaApriY1Block;
import net.pokefood.block.DisplaySodaApriW7Block;
import net.pokefood.block.DisplaySodaApriW6Block;
import net.pokefood.block.DisplaySodaApriW5Block;
import net.pokefood.block.DisplaySodaApriW4Block;
import net.pokefood.block.DisplaySodaApriW3Block;
import net.pokefood.block.DisplaySodaApriW2Block;
import net.pokefood.block.DisplaySodaApriW1Block;
import net.pokefood.block.DisplaySodaApriR7Block;
import net.pokefood.block.DisplaySodaApriR6Block;
import net.pokefood.block.DisplaySodaApriR5Block;
import net.pokefood.block.DisplaySodaApriR4Block;
import net.pokefood.block.DisplaySodaApriR3Block;
import net.pokefood.block.DisplaySodaApriR2Block;
import net.pokefood.block.DisplaySodaApriR1Block;
import net.pokefood.block.DisplaySodaApriP7Block;
import net.pokefood.block.DisplaySodaApriP6Block;
import net.pokefood.block.DisplaySodaApriP5Block;
import net.pokefood.block.DisplaySodaApriP4Block;
import net.pokefood.block.DisplaySodaApriP3Block;
import net.pokefood.block.DisplaySodaApriP2Block;
import net.pokefood.block.DisplaySodaApriP1Block;
import net.pokefood.block.DisplaySodaApriG7Block;
import net.pokefood.block.DisplaySodaApriG6Block;
import net.pokefood.block.DisplaySodaApriG5Block;
import net.pokefood.block.DisplaySodaApriG4Block;
import net.pokefood.block.DisplaySodaApriG3Block;
import net.pokefood.block.DisplaySodaApriG2Block;
import net.pokefood.block.DisplaySodaApriG1Block;
import net.pokefood.block.DisplaySodaApriD7Block;
import net.pokefood.block.DisplaySodaApriD6Block;
import net.pokefood.block.DisplaySodaApriD5Block;
import net.pokefood.block.DisplaySodaApriD4Block;
import net.pokefood.block.DisplaySodaApriD3Block;
import net.pokefood.block.DisplaySodaApriD2Block;
import net.pokefood.block.DisplaySodaApriD1Block;
import net.pokefood.block.DisplaySodaApriB7Block;
import net.pokefood.block.DisplaySodaApriB6Block;
import net.pokefood.block.DisplaySodaApriB5Block;
import net.pokefood.block.DisplaySodaApriB4Block;
import net.pokefood.block.DisplaySodaApriB3Block;
import net.pokefood.block.DisplaySodaApriB2Block;
import net.pokefood.block.DisplaySodaApriB1Block;
import net.pokefood.block.DisplayCasePuffs9Block;
import net.pokefood.block.DisplayCasePuffs8Block;
import net.pokefood.block.DisplayCasePuffs7Block;
import net.pokefood.block.DisplayCasePuffs6Block;
import net.pokefood.block.DisplayCasePuffs5Block;
import net.pokefood.block.DisplayCasePuffs4Block;
import net.pokefood.block.DisplayCasePuffs3Block;
import net.pokefood.block.DisplayCasePuffs2Block;
import net.pokefood.block.DisplayCasePuffs1Block;
import net.pokefood.block.DisplayCasePuffs14Block;
import net.pokefood.block.DisplayCasePuffs13Block;
import net.pokefood.block.DisplayCasePuffs12Block;
import net.pokefood.block.DisplayCasePuffs11Block;
import net.pokefood.block.DisplayCasePuffs10Block;
import net.pokefood.block.DisplayCasePuffs0Block;
import net.pokefood.block.DisplayCasePoffin9Block;
import net.pokefood.block.DisplayCasePoffin8Block;
import net.pokefood.block.DisplayCasePoffin7Block;
import net.pokefood.block.DisplayCasePoffin6Block;
import net.pokefood.block.DisplayCasePoffin5Block;
import net.pokefood.block.DisplayCasePoffin4Block;
import net.pokefood.block.DisplayCasePoffin3Block;
import net.pokefood.block.DisplayCasePoffin2Block;
import net.pokefood.block.DisplayCasePoffin1Block;
import net.pokefood.block.DisplayCasePoffin0Block;
import net.pokefood.block.DisplayCaseEmptyBlock;
import net.pokefood.block.CoolerYellowBlock;
import net.pokefood.block.CoolerRedBlock;
import net.pokefood.block.CoolerPinkBlock;
import net.pokefood.block.CoolerGreenBlock;
import net.pokefood.block.CoolerBlueBlock;
import net.pokefood.block.ConeDisplayBlock;
import net.pokefood.block.CoffeeTable8Block;
import net.pokefood.block.CoffeeTable7Block;
import net.pokefood.block.CoffeeTable6Block;
import net.pokefood.block.CoffeeTable5Block;
import net.pokefood.block.CoffeeTable4Block;
import net.pokefood.block.CoffeeTable3Block;
import net.pokefood.block.CoffeeTable2Block;
import net.pokefood.block.CoffeeTable1Block;
import net.pokefood.block.CoffeeTable10Block;
import net.pokefood.block.CoffeeTable0Block;
import net.pokefood.block.CoffeeMakerCookingBlock;
import net.pokefood.block.CoffeeMakerCookedBlock;
import net.pokefood.block.CoffeeMakerBlock;
import net.pokefood.block.CoffeeIcedBlock;
import net.pokefood.block.CoffeeBlock;
import net.pokefood.block.CidronadeBlock;
import net.pokefood.block.CherryInfusionBlock;
import net.pokefood.block.CherryCalcuimBeerBlock;
import net.pokefood.block.CardboardBoxBlock;
import net.pokefood.block.CarbonizerBottleBlock;
import net.pokefood.block.CandyBoxEmptyBlock;
import net.pokefood.block.CandyBoxBlock;
import net.pokefood.block.CalcuimStage3Block;
import net.pokefood.block.CalcuimStage2Block;
import net.pokefood.block.CalcuimStage1Block;
import net.pokefood.block.CalcuimStage0Block;
import net.pokefood.block.CalcuimPlantBlock;
import net.pokefood.block.CalcuimEmptyB9Block;
import net.pokefood.block.CalcuimEmptyB8Block;
import net.pokefood.block.CalcuimEmptyB7Block;
import net.pokefood.block.CalcuimEmptyB6Block;
import net.pokefood.block.CalcuimEmptyB5Block;
import net.pokefood.block.CalcuimEmptyB4Block;
import net.pokefood.block.CalcuimEmptyB3Block;
import net.pokefood.block.CalcuimEmptyB2Block;
import net.pokefood.block.CalcuimEmptyB1Block;
import net.pokefood.block.CalcuimEmptyB15Block;
import net.pokefood.block.CalcuimEmptyB14Block;
import net.pokefood.block.CalcuimEmptyB13Block;
import net.pokefood.block.CalcuimEmptyB12Block;
import net.pokefood.block.CalcuimEmptyB11Block;
import net.pokefood.block.CalcuimEmptyB10Block;
import net.pokefood.block.CalcuimEmptyB0Block;
import net.pokefood.block.CalcuimB9Block;
import net.pokefood.block.CalcuimB8Block;
import net.pokefood.block.CalcuimB7Block;
import net.pokefood.block.CalcuimB6Block;
import net.pokefood.block.CalcuimB5Block;
import net.pokefood.block.CalcuimB4Block;
import net.pokefood.block.CalcuimB3Block;
import net.pokefood.block.CalcuimB2Block;
import net.pokefood.block.CalcuimB1Block;
import net.pokefood.block.CalcuimB15Block;
import net.pokefood.block.CalcuimB14Block;
import net.pokefood.block.CalcuimB13Block;
import net.pokefood.block.CalcuimB12Block;
import net.pokefood.block.CalcuimB11Block;
import net.pokefood.block.CalcuimB10Block;
import net.pokefood.block.CalcuimB0Block;
import net.pokefood.block.BrandyBlock;
import net.pokefood.block.BlackTeaStage2Block;
import net.pokefood.block.BlackTeaStage1Block;
import net.pokefood.block.BlackTeaStage0Block;
import net.pokefood.block.BlackTeaBlock;
import net.pokefood.block.BigOvenBlock;
import net.pokefood.block.BigBagBlock;
import net.pokefood.block.BeerBlock;
import net.pokefood.block.Barstool9Block;
import net.pokefood.block.Barstool8Block;
import net.pokefood.block.Barstool7Block;
import net.pokefood.block.Barstool6Block;
import net.pokefood.block.Barstool5Block;
import net.pokefood.block.Barstool4Block;
import net.pokefood.block.Barstool3Block;
import net.pokefood.block.Barstool2Block;
import net.pokefood.block.Barstool1Block;
import net.pokefood.block.Barstool15Block;
import net.pokefood.block.Barstool14Block;
import net.pokefood.block.Barstool13Block;
import net.pokefood.block.Barstool12Block;
import net.pokefood.block.Barstool11Block;
import net.pokefood.block.Barstool10Block;
import net.pokefood.block.Barstool0Block;
import net.pokefood.block.BananaWoodTreeControlerBlock;
import net.pokefood.block.BananaWoodStrippedBlock;
import net.pokefood.block.BananaWoodBlock;
import net.pokefood.block.BananaUnripedBlock;
import net.pokefood.block.BananaTrapdoorBlock;
import net.pokefood.block.BananaTopStrippedBlock;
import net.pokefood.block.BananaTopBlock;
import net.pokefood.block.BananaTeaBeerBlock;
import net.pokefood.block.BananaStairsBlock;
import net.pokefood.block.BananaSlabBlock;
import net.pokefood.block.BananaRipedBlock;
import net.pokefood.block.BananaPressurePlateBlock;
import net.pokefood.block.BananaPlantBlock;
import net.pokefood.block.BananaPlanksBlock;
import net.pokefood.block.BananaLogStrippedBlock;
import net.pokefood.block.BananaLogBlock;
import net.pokefood.block.BananaLog3StrippedBlock;
import net.pokefood.block.BananaLog3Block;
import net.pokefood.block.BananaLog2StrippedBlock;
import net.pokefood.block.BananaLog2ControlerBlock;
import net.pokefood.block.BananaLog2Block;
import net.pokefood.block.BananaLeavesBlock;
import net.pokefood.block.BananaFenceGateBlock;
import net.pokefood.block.BananaFenceBlock;
import net.pokefood.block.BananaDoorBlock;
import net.pokefood.block.BananaButtonBlock;
import net.pokefood.block.ArceumBlock;
import net.pokefood.block.ApriJuiceYBlock;
import net.pokefood.block.ApriJuiceWBlock;
import net.pokefood.block.ApriJuiceRBlock;
import net.pokefood.block.ApriJuicePBlock;
import net.pokefood.block.ApriJuiceGBlock;
import net.pokefood.block.ApriJuiceDBlock;
import net.pokefood.block.ApriJuiceBBlock;
import net.pokefood.block.ApriAlcoholYBlock;
import net.pokefood.block.ApriAlcoholWBlock;
import net.pokefood.block.ApriAlcoholRBlock;
import net.pokefood.block.ApriAlcoholPBlock;
import net.pokefood.block.ApriAlcoholGBlock;
import net.pokefood.block.ApriAlcoholDBlock;
import net.pokefood.block.ApriAlcoholBBlock;
import net.pokefood.PokefoodMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class PokefoodModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PokefoodMod.MODID);
	public static final RegistryObject<Block> CONE_DISPLAY = REGISTRY.register("cone_display", () -> new ConeDisplayBlock());
	public static final RegistryObject<Block> POT_EMPTY = REGISTRY.register("pot_empty", () -> new PotEmptyBlock());
	public static final RegistryObject<Block> CARBONIZER = REGISTRY.register("carbonizer", () -> new CarbonizerBottleBlock());
	public static final RegistryObject<Block> OVEN = REGISTRY.register("oven", () -> new BigOvenBlock());
	public static final RegistryObject<Block> MIXER_RED = REGISTRY.register("mixer_red", () -> new MixerRedBlock());
	public static final RegistryObject<Block> MIXER_PINK = REGISTRY.register("mixer_pink", () -> new MixerPinkBlock());
	public static final RegistryObject<Block> MIXER_YELLOW = REGISTRY.register("mixer_yellow", () -> new MixerYellowBlock());
	public static final RegistryObject<Block> MIXER_GREEN = REGISTRY.register("mixer_green", () -> new MixerGreenBlock());
	public static final RegistryObject<Block> MIXER_BLUE = REGISTRY.register("mixer_blue", () -> new MixerBlueBlock());
	public static final RegistryObject<Block> KEG = REGISTRY.register("keg", () -> new KegBlock());
	public static final RegistryObject<Block> FRYER = REGISTRY.register("fryer", () -> new FryerBlock());
	public static final RegistryObject<Block> ICE_CREAM_MAKER = REGISTRY.register("ice_cream_maker", () -> new IceCreamMakerBlock());
	public static final RegistryObject<Block> COFFEE_MAKER = REGISTRY.register("coffee_maker", () -> new CoffeeMakerBlock());
	public static final RegistryObject<Block> KEG_FUNNEL = REGISTRY.register("keg_funnel", () -> new KegFunnelBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION = REGISTRY.register("ice_cream_extention", () -> new IceCreamExtentionBlock());
	public static final RegistryObject<Block> HEATER = REGISTRY.register("heater", () -> new HeaterBlock());
	public static final RegistryObject<Block> COOLER_BLUE = REGISTRY.register("cooler_blue", () -> new CoolerBlueBlock());
	public static final RegistryObject<Block> COOLER_GREEN = REGISTRY.register("cooler_green", () -> new CoolerGreenBlock());
	public static final RegistryObject<Block> COOLER_YELLOW = REGISTRY.register("cooler_yellow", () -> new CoolerYellowBlock());
	public static final RegistryObject<Block> COOLER_PINK = REGISTRY.register("cooler_pink", () -> new CoolerPinkBlock());
	public static final RegistryObject<Block> COOLER_RED = REGISTRY.register("cooler_red", () -> new CoolerRedBlock());
	public static final RegistryObject<Block> DISPLAY_CASE_EMPTY = REGISTRY.register("display_case_empty", () -> new DisplayCaseEmptyBlock());
	public static final RegistryObject<Block> CANDY_BOX_EMPTY = REGISTRY.register("candy_box_empty", () -> new CandyBoxEmptyBlock());
	public static final RegistryObject<Block> CANDY_BOX = REGISTRY.register("candy_box", () -> new CandyBoxBlock());
	public static final RegistryObject<Block> BIG_BAG = REGISTRY.register("big_bag", () -> new BigBagBlock());
	public static final RegistryObject<Block> CARDBOARD_BOX = REGISTRY.register("cardboard_box", () -> new CardboardBoxBlock());
	public static final RegistryObject<Block> PACK_EMPTY = REGISTRY.register("pack_empty", () -> new PackEmptyBlock());
	public static final RegistryObject<Block> PACK_APRI_D = REGISTRY.register("pack_apri_d", () -> new PackApriDBlock());
	public static final RegistryObject<Block> PACK_APRI_B = REGISTRY.register("pack_apri_b", () -> new PackApriBBlock());
	public static final RegistryObject<Block> PACK_APRI_G = REGISTRY.register("pack_apri_g", () -> new PackApriGBlock());
	public static final RegistryObject<Block> PACK_APRI_Y = REGISTRY.register("pack_apri_y", () -> new PackApriYBlock());
	public static final RegistryObject<Block> PACK_APRI_R = REGISTRY.register("pack_apri_r", () -> new PackApriRBlock());
	public static final RegistryObject<Block> PACK_APRI_P = REGISTRY.register("pack_apri_p", () -> new PackApriPBlock());
	public static final RegistryObject<Block> PACK_APRI_W = REGISTRY.register("pack_apri_w", () -> new PackApriWBlock());
	public static final RegistryObject<Block> PACK_TEA = REGISTRY.register("pack_tea", () -> new PackTeaBlock());
	public static final RegistryObject<Block> PACK_TEA_BLACK = REGISTRY.register("pack_tea_black", () -> new PackTeaBlackBlock());
	public static final RegistryObject<Block> PACK_TEA_ROSERADE = REGISTRY.register("pack_tea_roserade", () -> new PackTeaRoseradeBlock());
	public static final RegistryObject<Block> PACK_CHERRY = REGISTRY.register("pack_cherry", () -> new PackCherryBlock());
	public static final RegistryObject<Block> PACK_LEMONADE = REGISTRY.register("pack_lemonade", () -> new PackLemonadeBlock());
	public static final RegistryObject<Block> PACK_POP = REGISTRY.register("pack_pop", () -> new PackPopBlock());
	public static final RegistryObject<Block> PACK_COFFEE = REGISTRY.register("pack_coffee", () -> new PackCoffeeBlock());
	public static final RegistryObject<Block> PACK_LATTE = REGISTRY.register("pack_latte", () -> new PackLatteBlock());
	public static final RegistryObject<Block> COFFEE_TABLE_0 = REGISTRY.register("coffee_table_0", () -> new CoffeeTable0Block());
	public static final RegistryObject<Block> COFFEE_TABLE_1 = REGISTRY.register("coffee_table_1", () -> new CoffeeTable1Block());
	public static final RegistryObject<Block> COFFEE_TABLE_2 = REGISTRY.register("coffee_table_2", () -> new CoffeeTable2Block());
	public static final RegistryObject<Block> COFFEE_TABLE_3 = REGISTRY.register("coffee_table_3", () -> new CoffeeTable3Block());
	public static final RegistryObject<Block> COFFEE_TABLE_4 = REGISTRY.register("coffee_table_4", () -> new CoffeeTable4Block());
	public static final RegistryObject<Block> COFFEE_TABLE_5 = REGISTRY.register("coffee_table_5", () -> new CoffeeTable5Block());
	public static final RegistryObject<Block> COFFEE_TABLE_6 = REGISTRY.register("coffee_table_6", () -> new CoffeeTable6Block());
	public static final RegistryObject<Block> COFFEE_TABLE_7 = REGISTRY.register("coffee_table_7", () -> new CoffeeTable7Block());
	public static final RegistryObject<Block> COFFEE_TABLE_8 = REGISTRY.register("coffee_table_8", () -> new CoffeeTable8Block());
	public static final RegistryObject<Block> COFFEE_TABLE_10 = REGISTRY.register("coffee_table_10", () -> new CoffeeTable10Block());
	public static final RegistryObject<Block> BARSTOOL_0 = REGISTRY.register("barstool_0", () -> new Barstool0Block());
	public static final RegistryObject<Block> BARSTOOL_1 = REGISTRY.register("barstool_1", () -> new Barstool1Block());
	public static final RegistryObject<Block> BARSTOOL_2 = REGISTRY.register("barstool_2", () -> new Barstool2Block());
	public static final RegistryObject<Block> BARSTOOL_3 = REGISTRY.register("barstool_3", () -> new Barstool3Block());
	public static final RegistryObject<Block> BARSTOOL_4 = REGISTRY.register("barstool_4", () -> new Barstool4Block());
	public static final RegistryObject<Block> BARSTOOL_6 = REGISTRY.register("barstool_6", () -> new Barstool6Block());
	public static final RegistryObject<Block> BARSTOOL_5 = REGISTRY.register("barstool_5", () -> new Barstool5Block());
	public static final RegistryObject<Block> BARSTOOL_7 = REGISTRY.register("barstool_7", () -> new Barstool7Block());
	public static final RegistryObject<Block> BARSTOOL_8 = REGISTRY.register("barstool_8", () -> new Barstool8Block());
	public static final RegistryObject<Block> BARSTOOL_9 = REGISTRY.register("barstool_9", () -> new Barstool9Block());
	public static final RegistryObject<Block> BARSTOOL_10 = REGISTRY.register("barstool_10", () -> new Barstool10Block());
	public static final RegistryObject<Block> BARSTOOL_11 = REGISTRY.register("barstool_11", () -> new Barstool11Block());
	public static final RegistryObject<Block> BARSTOOL_12 = REGISTRY.register("barstool_12", () -> new Barstool12Block());
	public static final RegistryObject<Block> BARSTOOL_13 = REGISTRY.register("barstool_13", () -> new Barstool13Block());
	public static final RegistryObject<Block> BARSTOOL_14 = REGISTRY.register("barstool_14", () -> new Barstool14Block());
	public static final RegistryObject<Block> BARSTOOL_15 = REGISTRY.register("barstool_15", () -> new Barstool15Block());
	public static final RegistryObject<Block> TEA = REGISTRY.register("tea", () -> new TeaBlock());
	public static final RegistryObject<Block> BLACK_TEA = REGISTRY.register("black_tea", () -> new BlackTeaBlock());
	public static final RegistryObject<Block> ROSERADE_TEA = REGISTRY.register("roserade_tea", () -> new RoseradeTeaBlock());
	public static final RegistryObject<Block> COFFEE = REGISTRY.register("coffee", () -> new CoffeeBlock());
	public static final RegistryObject<Block> COFFEE_ICED = REGISTRY.register("coffee_iced", () -> new CoffeeIcedBlock());
	public static final RegistryObject<Block> LATTE = REGISTRY.register("latte", () -> new LatteBlock());
	public static final RegistryObject<Block> LEMONADE = REGISTRY.register("lemonade", () -> new LemonadeBlock());
	public static final RegistryObject<Block> FRESH_WATER = REGISTRY.register("fresh_water", () -> new FreshWaterBlock());
	public static final RegistryObject<Block> CHERRY_INFUSION = REGISTRY.register("cherry_infusion", () -> new CherryInfusionBlock());
	public static final RegistryObject<Block> APRI_JUICE_B = REGISTRY.register("apri_juice_b", () -> new ApriJuiceBBlock());
	public static final RegistryObject<Block> APRI_JUICE_D = REGISTRY.register("apri_juice_d", () -> new ApriJuiceDBlock());
	public static final RegistryObject<Block> APRI_JUICE_Y = REGISTRY.register("apri_juice_y", () -> new ApriJuiceYBlock());
	public static final RegistryObject<Block> APRI_JUICE_G = REGISTRY.register("apri_juice_g", () -> new ApriJuiceGBlock());
	public static final RegistryObject<Block> APRI_JUICE_R = REGISTRY.register("apri_juice_r", () -> new ApriJuiceRBlock());
	public static final RegistryObject<Block> APRI_JUICE_P = REGISTRY.register("apri_juice_p", () -> new ApriJuicePBlock());
	public static final RegistryObject<Block> APRI_JUICE_W = REGISTRY.register("apri_juice_w", () -> new ApriJuiceWBlock());
	public static final RegistryObject<Block> MALT = REGISTRY.register("malt", () -> new MaltBlock());
	public static final RegistryObject<Block> BEER = REGISTRY.register("beer", () -> new BeerBlock());
	public static final RegistryObject<Block> BANANA_TEA_BEER = REGISTRY.register("banana_tea_beer", () -> new BananaTeaBeerBlock());
	public static final RegistryObject<Block> CHERRY_CALCUIM_BEER = REGISTRY.register("cherry_calcuim_beer", () -> new CherryCalcuimBeerBlock());
	public static final RegistryObject<Block> BRANDY = REGISTRY.register("brandy", () -> new BrandyBlock());
	public static final RegistryObject<Block> CIDRONADE = REGISTRY.register("cidronade", () -> new CidronadeBlock());
	public static final RegistryObject<Block> ARCEUM = REGISTRY.register("arceum", () -> new ArceumBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_D = REGISTRY.register("apri_alcohol_d", () -> new ApriAlcoholDBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_B = REGISTRY.register("apri_alcohol_b", () -> new ApriAlcoholBBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_G = REGISTRY.register("apri_alcohol_g", () -> new ApriAlcoholGBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_Y = REGISTRY.register("apri_alcohol_y", () -> new ApriAlcoholYBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_R = REGISTRY.register("apri_alcohol_r", () -> new ApriAlcoholRBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_P = REGISTRY.register("apri_alcohol_p", () -> new ApriAlcoholPBlock());
	public static final RegistryObject<Block> APRI_ALCOHOL_W = REGISTRY.register("apri_alcohol_w", () -> new ApriAlcoholWBlock());
	public static final RegistryObject<Block> BANANA_WOOD = REGISTRY.register("banana_wood", () -> new BananaWoodBlock());
	public static final RegistryObject<Block> BANANA_LOG = REGISTRY.register("banana_log", () -> new BananaLogBlock());
	public static final RegistryObject<Block> BANANA_LOG_2 = REGISTRY.register("banana_log_2", () -> new BananaLog2Block());
	public static final RegistryObject<Block> BANANA_LOG_3 = REGISTRY.register("banana_log_3", () -> new BananaLog3Block());
	public static final RegistryObject<Block> BANANA_WOOD_STRIPPED = REGISTRY.register("banana_wood_stripped", () -> new BananaWoodStrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_STRIPPED = REGISTRY.register("banana_log_stripped", () -> new BananaLogStrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_2_STRIPPED = REGISTRY.register("banana_log_2_stripped", () -> new BananaLog2StrippedBlock());
	public static final RegistryObject<Block> BANANA_LOG_3_STRIPPED = REGISTRY.register("banana_log_3_stripped", () -> new BananaLog3StrippedBlock());
	public static final RegistryObject<Block> BANANA_PLANKS = REGISTRY.register("banana_planks", () -> new BananaPlanksBlock());
	public static final RegistryObject<Block> BANANA_STAIRS = REGISTRY.register("banana_stairs", () -> new BananaStairsBlock());
	public static final RegistryObject<Block> BANANA_SLAB = REGISTRY.register("banana_slab", () -> new BananaSlabBlock());
	public static final RegistryObject<Block> BANANA_FENCE = REGISTRY.register("banana_fence", () -> new BananaFenceBlock());
	public static final RegistryObject<Block> BANANA_BUTTON = REGISTRY.register("banana_button", () -> new BananaButtonBlock());
	public static final RegistryObject<Block> BANANA_PRESSURE_PLATE = REGISTRY.register("banana_pressure_plate", () -> new BananaPressurePlateBlock());
	public static final RegistryObject<Block> BANANA_DOOR = REGISTRY.register("banana_door", () -> new BananaDoorBlock());
	public static final RegistryObject<Block> BANANA_TRAPDOOR = REGISTRY.register("banana_trapdoor", () -> new BananaTrapdoorBlock());
	public static final RegistryObject<Block> BANANA_FENCE_GATE = REGISTRY.register("banana_fence_gate", () -> new BananaFenceGateBlock());
	public static final RegistryObject<Block> TEA_STAGE_0 = REGISTRY.register("tea_stage_0", () -> new TeaStage0Block());
	public static final RegistryObject<Block> TEA_STAGE_1 = REGISTRY.register("tea_stage_1", () -> new TeaStage1Block());
	public static final RegistryObject<Block> TEA_STAGE_2 = REGISTRY.register("tea_stage_2", () -> new TeaStage2Block());
	public static final RegistryObject<Block> BLACK_TEA_STAGE_0 = REGISTRY.register("black_tea_stage_0", () -> new BlackTeaStage0Block());
	public static final RegistryObject<Block> BLACK_TEA_STAGE_1 = REGISTRY.register("black_tea_stage_1", () -> new BlackTeaStage1Block());
	public static final RegistryObject<Block> BLACK_TEA_STAGE_2 = REGISTRY.register("black_tea_stage_2", () -> new BlackTeaStage2Block());
	public static final RegistryObject<Block> LEMON_STAGE_0 = REGISTRY.register("lemon_stage_0", () -> new LemonStage0Block());
	public static final RegistryObject<Block> LEMON_STAGE_1 = REGISTRY.register("lemon_stage_1", () -> new LemonStage1Block());
	public static final RegistryObject<Block> LEMON_STAGE_2 = REGISTRY.register("lemon_stage_2", () -> new LemonStage2Block());
	public static final RegistryObject<Block> LEMON_STAGE_3 = REGISTRY.register("lemon_stage_3", () -> new LemonStage3Block());
	public static final RegistryObject<Block> LEMON_STAGE_4 = REGISTRY.register("lemon_stage_4", () -> new LemonStage4Block());
	public static final RegistryObject<Block> LEMON_STAGE_5 = REGISTRY.register("lemon_stage_5", () -> new LemonStage5Block());
	public static final RegistryObject<Block> LEMON_STAGE_6 = REGISTRY.register("lemon_stage_6", () -> new LemonStage6Block());
	public static final RegistryObject<Block> CALCUIM_STAGE_0 = REGISTRY.register("calcuim_stage_0", () -> new CalcuimStage0Block());
	public static final RegistryObject<Block> CALCUIM_STAGE_1 = REGISTRY.register("calcuim_stage_1", () -> new CalcuimStage1Block());
	public static final RegistryObject<Block> CALCUIM_STAGE_2 = REGISTRY.register("calcuim_stage_2", () -> new CalcuimStage2Block());
	public static final RegistryObject<Block> CALCUIM_STAGE_3 = REGISTRY.register("calcuim_stage_3", () -> new CalcuimStage3Block());
	public static final RegistryObject<Block> CALCUIM_PLANT = REGISTRY.register("calcuim_plant", () -> new CalcuimPlantBlock());
	public static final RegistryObject<Block> POT_WATER = REGISTRY.register("pot_water", () -> new PotWaterBlock());
	public static final RegistryObject<Block> POT_WATER_FIRED = REGISTRY.register("pot_water_fired", () -> new PotWaterFiredBlock());
	public static final RegistryObject<Block> POT_TEA = REGISTRY.register("pot_tea", () -> new PotTeaBlock());
	public static final RegistryObject<Block> POT_TEA_FIRED = REGISTRY.register("pot_tea_fired", () -> new PotTeaFiredBlock());
	public static final RegistryObject<Block> POT_BLACK_TEA = REGISTRY.register("pot_black_tea", () -> new PotBlackTeaBlock());
	public static final RegistryObject<Block> POT_BLACK_TEA_FIRED = REGISTRY.register("pot_black_tea_fired", () -> new PotBlackTeaFiredBlock());
	public static final RegistryObject<Block> POT_TEA_COOKED = REGISTRY.register("pot_tea_cooked", () -> new PotTeaCookedBlock());
	public static final RegistryObject<Block> POT_BLACK_TEA_COOKED = REGISTRY.register("pot_black_tea_cooked", () -> new PotBlackTeaCookedBlock());
	public static final RegistryObject<Block> POT_FRESH_WATER = REGISTRY.register("pot_fresh_water", () -> new PotFreshWaterBlock());
	public static final RegistryObject<Block> POT_WATER_SUGAR = REGISTRY.register("pot_water_sugar", () -> new PotWaterSugarBlock());
	public static final RegistryObject<Block> POT_WATER_LEMON = REGISTRY.register("pot_water_lemon", () -> new PotWaterLemonBlock());
	public static final RegistryObject<Block> POT_LEMONADE = REGISTRY.register("pot_lemonade", () -> new PotLemonadeBlock());
	public static final RegistryObject<Block> POT_LEMONADE_COOKED = REGISTRY.register("pot_lemonade_cooked", () -> new PotLemonadeCookedBlock());
	public static final RegistryObject<Block> POT_ROSERADE_TEA = REGISTRY.register("pot_roserade_tea", () -> new PotRoseradeTeaBlock());
	public static final RegistryObject<Block> POT_ROSERADE_TEA_FIRED = REGISTRY.register("pot_roserade_tea_fired", () -> new PotRoseradeTeaFiredBlock());
	public static final RegistryObject<Block> POT_ROSERADE_TEA_COOKED = REGISTRY.register("pot_roserade_tea_cooked", () -> new PotRoseradeTeaCookedBlock());
	public static final RegistryObject<Block> KEG_2 = REGISTRY.register("keg_2", () -> new Keg2Block());
	public static final RegistryObject<Block> KEG_3 = REGISTRY.register("keg_3", () -> new Keg3Block());
	public static final RegistryObject<Block> KEG_4 = REGISTRY.register("keg_4", () -> new Keg4Block());
	public static final RegistryObject<Block> KEG_5 = REGISTRY.register("keg_5", () -> new Keg5Block());
	public static final RegistryObject<Block> KEG_6 = REGISTRY.register("keg_6", () -> new Keg6Block());
	public static final RegistryObject<Block> KEG_7 = REGISTRY.register("keg_7", () -> new Keg7Block());
	public static final RegistryObject<Block> POT_MALT = REGISTRY.register("pot_malt", () -> new PotMaltBlock());
	public static final RegistryObject<Block> POT_MALT_FIRED = REGISTRY.register("pot_malt_fired", () -> new PotMaltFiredBlock());
	public static final RegistryObject<Block> POT_MALT_COOKED = REGISTRY.register("pot_malt_cooked", () -> new PotMaltCookedBlock());
	public static final RegistryObject<Block> KEG_FUNNEL_UP = REGISTRY.register("keg_funnel_up", () -> new KegFunnelUpBlock());
	public static final RegistryObject<Block> KEG_FUNNEL_FRONT = REGISTRY.register("keg_funnel_front", () -> new KegFunnelFrontBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_B = REGISTRY.register("ice_cream_extention_apri_b", () -> new IceCreamExtentionApriBBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_D = REGISTRY.register("ice_cream_extention_apri_d", () -> new IceCreamExtentionApriDBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_G = REGISTRY.register("ice_cream_extention_apri_g", () -> new IceCreamExtentionApriGBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_P = REGISTRY.register("ice_cream_extention_apri_p", () -> new IceCreamExtentionApriPBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_R = REGISTRY.register("ice_cream_extention_apri_r", () -> new IceCreamExtentionApriRBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_W = REGISTRY.register("ice_cream_extention_apri_w", () -> new IceCreamExtentionApriWBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_APRI_Y = REGISTRY.register("ice_cream_extention_apri_y", () -> new IceCreamExtentionApriYBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_LEMONADE = REGISTRY.register("ice_cream_extention_lemonade", () -> new IceCreamExtentionLemonadeBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_TEA = REGISTRY.register("ice_cream_extention_tea", () -> new IceCreamExtentionTeaBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_TEA_B = REGISTRY.register("ice_cream_extention_tea_b", () -> new IceCreamExtentionTeaBBlock());
	public static final RegistryObject<Block> ICE_CREAM_EXTENTION_TEA_R = REGISTRY.register("ice_cream_extention_tea_r", () -> new IceCreamExtentionTeaRBlock());
	public static final RegistryObject<Block> COFFEE_MAKER_COOKING = REGISTRY.register("coffee_maker_cooking", () -> new CoffeeMakerCookingBlock());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_0 = REGISTRY.register("display_case_puffs_0", () -> new DisplayCasePuffs0Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_1 = REGISTRY.register("display_case_puffs_1", () -> new DisplayCasePuffs1Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_2 = REGISTRY.register("display_case_puffs_2", () -> new DisplayCasePuffs2Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_3 = REGISTRY.register("display_case_puffs_3", () -> new DisplayCasePuffs3Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_4 = REGISTRY.register("display_case_puffs_4", () -> new DisplayCasePuffs4Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_5 = REGISTRY.register("display_case_puffs_5", () -> new DisplayCasePuffs5Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_6 = REGISTRY.register("display_case_puffs_6", () -> new DisplayCasePuffs6Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_7 = REGISTRY.register("display_case_puffs_7", () -> new DisplayCasePuffs7Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_8 = REGISTRY.register("display_case_puffs_8", () -> new DisplayCasePuffs8Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_9 = REGISTRY.register("display_case_puffs_9", () -> new DisplayCasePuffs9Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_10 = REGISTRY.register("display_case_puffs_10", () -> new DisplayCasePuffs10Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_11 = REGISTRY.register("display_case_puffs_11", () -> new DisplayCasePuffs11Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_12 = REGISTRY.register("display_case_puffs_12", () -> new DisplayCasePuffs12Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_13 = REGISTRY.register("display_case_puffs_13", () -> new DisplayCasePuffs13Block());
	public static final RegistryObject<Block> DISPLAY_CASE_PUFFS_14 = REGISTRY.register("display_case_puffs_14", () -> new DisplayCasePuffs14Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_0 = REGISTRY.register("display_case_poffin_0", () -> new DisplayCasePoffin0Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_1 = REGISTRY.register("display_case_poffin_1", () -> new DisplayCasePoffin1Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_2 = REGISTRY.register("display_case_poffin_2", () -> new DisplayCasePoffin2Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_3 = REGISTRY.register("display_case_poffin_3", () -> new DisplayCasePoffin3Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_4 = REGISTRY.register("display_case_poffin_4", () -> new DisplayCasePoffin4Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_5 = REGISTRY.register("display_case_poffin_5", () -> new DisplayCasePoffin5Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_6 = REGISTRY.register("display_case_poffin_6", () -> new DisplayCasePoffin6Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_7 = REGISTRY.register("display_case_poffin_7", () -> new DisplayCasePoffin7Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_8 = REGISTRY.register("display_case_poffin_8", () -> new DisplayCasePoffin8Block());
	public static final RegistryObject<Block> DISPLAY_CASE_POFFIN_9 = REGISTRY.register("display_case_poffin_9", () -> new DisplayCasePoffin9Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_1 = REGISTRY.register("display_soda_pop_1", () -> new DisplaySodaPop1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_2 = REGISTRY.register("display_soda_pop_2", () -> new DisplaySodaPop2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_3 = REGISTRY.register("display_soda_pop_3", () -> new DisplaySodaPop3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_4 = REGISTRY.register("display_soda_pop_4", () -> new DisplaySodaPop4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_5 = REGISTRY.register("display_soda_pop_5", () -> new DisplaySodaPop5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_6 = REGISTRY.register("display_soda_pop_6", () -> new DisplaySodaPop6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_POP_7 = REGISTRY.register("display_soda_pop_7", () -> new DisplaySodaPop7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_1 = REGISTRY.register("display_soda_tea_1", () -> new DisplaySodaTea1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_2 = REGISTRY.register("display_soda_tea_2", () -> new DisplaySodaTea2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_3 = REGISTRY.register("display_soda_tea_3", () -> new DisplaySodaTea3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_4 = REGISTRY.register("display_soda_tea_4", () -> new DisplaySodaTea4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_5 = REGISTRY.register("display_soda_tea_5", () -> new DisplaySodaTea5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_6 = REGISTRY.register("display_soda_tea_6", () -> new DisplaySodaTea6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_7 = REGISTRY.register("display_soda_tea_7", () -> new DisplaySodaTea7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_1 = REGISTRY.register("display_soda_tea_black_1", () -> new DisplaySodaTeaBlack1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_2 = REGISTRY.register("display_soda_tea_black_2", () -> new DisplaySodaTeaBlack2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_3 = REGISTRY.register("display_soda_tea_black_3", () -> new DisplaySodaTeaBlack3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_4 = REGISTRY.register("display_soda_tea_black_4", () -> new DisplaySodaTeaBlack4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_5 = REGISTRY.register("display_soda_tea_black_5", () -> new DisplaySodaTeaBlack5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_6 = REGISTRY.register("display_soda_tea_black_6", () -> new DisplaySodaTeaBlack6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_BLACK_7 = REGISTRY.register("display_soda_tea_black_7", () -> new DisplaySodaTeaBlack7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_1 = REGISTRY.register("display_soda_tea_roserade_1", () -> new DisplaySodaTeaRoserade1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_2 = REGISTRY.register("display_soda_tea_roserade_2", () -> new DisplaySodaTeaRoserade2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_3 = REGISTRY.register("display_soda_tea_roserade_3", () -> new DisplaySodaTeaRoserade3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_4 = REGISTRY.register("display_soda_tea_roserade_4", () -> new DisplaySodaTeaRoserade4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_5 = REGISTRY.register("display_soda_tea_roserade_5", () -> new DisplaySodaTeaRoserade5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_6 = REGISTRY.register("display_soda_tea_roserade_6", () -> new DisplaySodaTeaRoserade6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_TEA_ROSERADE_7 = REGISTRY.register("display_soda_tea_roserade_7", () -> new DisplaySodaTeaRoserade7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_1 = REGISTRY.register("display_soda_lemonade_1", () -> new DisplaySodaLemonade1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_2 = REGISTRY.register("display_soda_lemonade_2", () -> new DisplaySodaLemonade2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_3 = REGISTRY.register("display_soda_lemonade_3", () -> new DisplaySodaLemonade3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_4 = REGISTRY.register("display_soda_lemonade_4", () -> new DisplaySodaLemonade4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_5 = REGISTRY.register("display_soda_lemonade_5", () -> new DisplaySodaLemonade5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_6 = REGISTRY.register("display_soda_lemonade_6", () -> new DisplaySodaLemonade6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_LEMONADE_7 = REGISTRY.register("display_soda_lemonade_7", () -> new DisplaySodaLemonade7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_1 = REGISTRY.register("display_soda_apri_d_1", () -> new DisplaySodaApriD1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_2 = REGISTRY.register("display_soda_apri_d_2", () -> new DisplaySodaApriD2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_3 = REGISTRY.register("display_soda_apri_d_3", () -> new DisplaySodaApriD3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_4 = REGISTRY.register("display_soda_apri_d_4", () -> new DisplaySodaApriD4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_5 = REGISTRY.register("display_soda_apri_d_5", () -> new DisplaySodaApriD5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_6 = REGISTRY.register("display_soda_apri_d_6", () -> new DisplaySodaApriD6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_D_7 = REGISTRY.register("display_soda_apri_d_7", () -> new DisplaySodaApriD7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_1 = REGISTRY.register("display_soda_apri_b_1", () -> new DisplaySodaApriB1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_2 = REGISTRY.register("display_soda_apri_b_2", () -> new DisplaySodaApriB2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_3 = REGISTRY.register("display_soda_apri_b_3", () -> new DisplaySodaApriB3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_4 = REGISTRY.register("display_soda_apri_b_4", () -> new DisplaySodaApriB4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_5 = REGISTRY.register("display_soda_apri_b_5", () -> new DisplaySodaApriB5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_6 = REGISTRY.register("display_soda_apri_b_6", () -> new DisplaySodaApriB6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_B_7 = REGISTRY.register("display_soda_apri_b_7", () -> new DisplaySodaApriB7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_1 = REGISTRY.register("display_soda_apri_g_1", () -> new DisplaySodaApriG1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_2 = REGISTRY.register("display_soda_apri_g_2", () -> new DisplaySodaApriG2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_3 = REGISTRY.register("display_soda_apri_g_3", () -> new DisplaySodaApriG3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_4 = REGISTRY.register("display_soda_apri_g_4", () -> new DisplaySodaApriG4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_5 = REGISTRY.register("display_soda_apri_g_5", () -> new DisplaySodaApriG5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_6 = REGISTRY.register("display_soda_apri_g_6", () -> new DisplaySodaApriG6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_G_7 = REGISTRY.register("display_soda_apri_g_7", () -> new DisplaySodaApriG7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_1 = REGISTRY.register("display_soda_apri_y_1", () -> new DisplaySodaApriY1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_2 = REGISTRY.register("display_soda_apri_y_2", () -> new DisplaySodaApriY2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_3 = REGISTRY.register("display_soda_apri_y_3", () -> new DisplaySodaApriY3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_4 = REGISTRY.register("display_soda_apri_y_4", () -> new DisplaySodaApriY4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_5 = REGISTRY.register("display_soda_apri_y_5", () -> new DisplaySodaApriY5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_6 = REGISTRY.register("display_soda_apri_y_6", () -> new DisplaySodaApriY6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_Y_7 = REGISTRY.register("display_soda_apri_y_7", () -> new DisplaySodaApriY7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_1 = REGISTRY.register("display_soda_apri_r_1", () -> new DisplaySodaApriR1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_2 = REGISTRY.register("display_soda_apri_r_2", () -> new DisplaySodaApriR2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_3 = REGISTRY.register("display_soda_apri_r_3", () -> new DisplaySodaApriR3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_4 = REGISTRY.register("display_soda_apri_r_4", () -> new DisplaySodaApriR4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_5 = REGISTRY.register("display_soda_apri_r_5", () -> new DisplaySodaApriR5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_6 = REGISTRY.register("display_soda_apri_r_6", () -> new DisplaySodaApriR6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_R_7 = REGISTRY.register("display_soda_apri_r_7", () -> new DisplaySodaApriR7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_1 = REGISTRY.register("display_soda_apri_p_1", () -> new DisplaySodaApriP1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_2 = REGISTRY.register("display_soda_apri_p_2", () -> new DisplaySodaApriP2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_3 = REGISTRY.register("display_soda_apri_p_3", () -> new DisplaySodaApriP3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_4 = REGISTRY.register("display_soda_apri_p_4", () -> new DisplaySodaApriP4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_5 = REGISTRY.register("display_soda_apri_p_5", () -> new DisplaySodaApriP5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_6 = REGISTRY.register("display_soda_apri_p_6", () -> new DisplaySodaApriP6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_P_7 = REGISTRY.register("display_soda_apri_p_7", () -> new DisplaySodaApriP7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_1 = REGISTRY.register("display_soda_apri_w_1", () -> new DisplaySodaApriW1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_2 = REGISTRY.register("display_soda_apri_w_2", () -> new DisplaySodaApriW2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_3 = REGISTRY.register("display_soda_apri_w_3", () -> new DisplaySodaApriW3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_4 = REGISTRY.register("display_soda_apri_w_4", () -> new DisplaySodaApriW4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_5 = REGISTRY.register("display_soda_apri_w_5", () -> new DisplaySodaApriW5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_6 = REGISTRY.register("display_soda_apri_w_6", () -> new DisplaySodaApriW6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_APRI_W_7 = REGISTRY.register("display_soda_apri_w_7", () -> new DisplaySodaApriW7Block());
	public static final RegistryObject<Block> BANANA_LEAVES = REGISTRY.register("banana_leaves", () -> new BananaLeavesBlock());
	public static final RegistryObject<Block> BANANA_TOP = REGISTRY.register("banana_top", () -> new BananaTopBlock());
	public static final RegistryObject<Block> BANANA_UNRIPED = REGISTRY.register("banana_unriped", () -> new BananaUnripedBlock());
	public static final RegistryObject<Block> BANANA_RIPED = REGISTRY.register("banana_riped", () -> new BananaRipedBlock());
	public static final RegistryObject<Block> BANANA_WOOD_TREE_CONTROLER = REGISTRY.register("banana_wood_tree_controler", () -> new BananaWoodTreeControlerBlock());
	public static final RegistryObject<Block> BANANA_LOG_2_CONTROLER = REGISTRY.register("banana_log_2_controler", () -> new BananaLog2ControlerBlock());
	public static final RegistryObject<Block> BANANA_PLANT = REGISTRY.register("banana_plant", () -> new BananaPlantBlock());
	public static final RegistryObject<Block> BANANA_TOP_STRIPPED = REGISTRY.register("banana_top_stripped", () -> new BananaTopStrippedBlock());
	public static final RegistryObject<Block> COFFEE_MAKER_COOKED = REGISTRY.register("coffee_maker_cooked", () -> new CoffeeMakerCookedBlock());
	public static final RegistryObject<Block> LEEK_STAGE_0 = REGISTRY.register("leek_stage_0", () -> new LeekStage0Block());
	public static final RegistryObject<Block> LEEK_STAGE_1 = REGISTRY.register("leek_stage_1", () -> new LeekStage1Block());
	public static final RegistryObject<Block> LEEK_STAGE_2 = REGISTRY.register("leek_stage_2", () -> new LeekStage2Block());
	public static final RegistryObject<Block> LEEK_STAGE_3 = REGISTRY.register("leek_stage_3", () -> new LeekStage3Block());
	public static final RegistryObject<Block> POT_CHERRY = REGISTRY.register("pot_cherry", () -> new PotCherryBlock());
	public static final RegistryObject<Block> POT_CHERRY_FIRED = REGISTRY.register("pot_cherry_fired", () -> new PotCherryFiredBlock());
	public static final RegistryObject<Block> POT_CHERRY_COOKED = REGISTRY.register("pot_cherry_cooked", () -> new PotCherryCookedBlock());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_1 = REGISTRY.register("display_soda_cherry_1", () -> new DisplaySodaCherry1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_2 = REGISTRY.register("display_soda_cherry_2", () -> new DisplaySodaCherry2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_3 = REGISTRY.register("display_soda_cherry_3", () -> new DisplaySodaCherry3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_4 = REGISTRY.register("display_soda_cherry_4", () -> new DisplaySodaCherry4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_5 = REGISTRY.register("display_soda_cherry_5", () -> new DisplaySodaCherry5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_6 = REGISTRY.register("display_soda_cherry_6", () -> new DisplaySodaCherry6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_CHERRY_7 = REGISTRY.register("display_soda_cherry_7", () -> new DisplaySodaCherry7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_1 = REGISTRY.register("display_soda_sombrine_1", () -> new DisplaySodaSombrine1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_2 = REGISTRY.register("display_soda_sombrine_2", () -> new DisplaySodaSombrine2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_3 = REGISTRY.register("display_soda_sombrine_3", () -> new DisplaySodaSombrine3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_4 = REGISTRY.register("display_soda_sombrine_4", () -> new DisplaySodaSombrine4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_5 = REGISTRY.register("display_soda_sombrine_5", () -> new DisplaySodaSombrine5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_6 = REGISTRY.register("display_soda_sombrine_6", () -> new DisplaySodaSombrine6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRINE_7 = REGISTRY.register("display_soda_sombrine_7", () -> new DisplaySodaSombrine7Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_1 = REGISTRY.register("display_soda_sombrade_1", () -> new DisplaySodaSombrade1Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_2 = REGISTRY.register("display_soda_sombrade_2", () -> new DisplaySodaSombrade2Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_3 = REGISTRY.register("display_soda_sombrade_3", () -> new DisplaySodaSombrade3Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_4 = REGISTRY.register("display_soda_sombrade_4", () -> new DisplaySodaSombrade4Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_5 = REGISTRY.register("display_soda_sombrade_5", () -> new DisplaySodaSombrade5Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_6 = REGISTRY.register("display_soda_sombrade_6", () -> new DisplaySodaSombrade6Block());
	public static final RegistryObject<Block> DISPLAY_SODA_SOMBRADE_7 = REGISTRY.register("display_soda_sombrade_7", () -> new DisplaySodaSombrade7Block());
	public static final RegistryObject<Block> PACK_APRI_B_4 = REGISTRY.register("pack_apri_b_4", () -> new PackApriB4Block());
	public static final RegistryObject<Block> PACK_APRI_D_4 = REGISTRY.register("pack_apri_d_4", () -> new PackApriD4Block());
	public static final RegistryObject<Block> PACK_APRI_G_4 = REGISTRY.register("pack_apri_g_4", () -> new PackApriG4Block());
	public static final RegistryObject<Block> PACK_APRI_Y_4 = REGISTRY.register("pack_apri_y_4", () -> new PackApriY4Block());
	public static final RegistryObject<Block> PACK_APRI_R_4 = REGISTRY.register("pack_apri_r_4", () -> new PackApriR4Block());
	public static final RegistryObject<Block> PACK_APRI_P_4 = REGISTRY.register("pack_apri_p_4", () -> new PackApriP4Block());
	public static final RegistryObject<Block> PACK_APRI_W_4 = REGISTRY.register("pack_apri_w_4", () -> new PackApriW4Block());
	public static final RegistryObject<Block> PACK_APRI_B_8 = REGISTRY.register("pack_apri_b_8", () -> new PackApriB8Block());
	public static final RegistryObject<Block> PACK_APRI_D_8 = REGISTRY.register("pack_apri_d_8", () -> new PackApriD8Block());
	public static final RegistryObject<Block> PACK_APRI_G_8 = REGISTRY.register("pack_apri_g_8", () -> new PackApriG8Block());
	public static final RegistryObject<Block> PACK_APRI_Y_8 = REGISTRY.register("pack_apri_y_8", () -> new PackApriY8Block());
	public static final RegistryObject<Block> PACK_APRI_R_8 = REGISTRY.register("pack_apri_r_8", () -> new PackApriR8Block());
	public static final RegistryObject<Block> PACK_APRI_P_8 = REGISTRY.register("pack_apri_p_8", () -> new PackApriP8Block());
	public static final RegistryObject<Block> PACK_APRI_W_8 = REGISTRY.register("pack_apri_w_8", () -> new PackApriW8Block());
	public static final RegistryObject<Block> PACK_TEA_4 = REGISTRY.register("pack_tea_4", () -> new PackTea4Block());
	public static final RegistryObject<Block> PACK_TEA_8 = REGISTRY.register("pack_tea_8", () -> new PackTea8Block());
	public static final RegistryObject<Block> PACK_TEA_BLACK_4 = REGISTRY.register("pack_tea_black_4", () -> new PackTeaBlack4Block());
	public static final RegistryObject<Block> PACK_TEA_BLACK_8 = REGISTRY.register("pack_tea_black_8", () -> new PackTeaBlack8Block());
	public static final RegistryObject<Block> PACK_TEA_ROSERADE_4 = REGISTRY.register("pack_tea_roserade_4", () -> new PackTeaRoserade4Block());
	public static final RegistryObject<Block> PACK_TEA_ROSERADE_8 = REGISTRY.register("pack_tea_roserade_8", () -> new PackTeaRoserade8Block());
	public static final RegistryObject<Block> PACK_CHERRY_4 = REGISTRY.register("pack_cherry_4", () -> new PackCherry4Block());
	public static final RegistryObject<Block> PACK_CHERRY_8 = REGISTRY.register("pack_cherry_8", () -> new PackCherry8Block());
	public static final RegistryObject<Block> PACK_LEMONADE_4 = REGISTRY.register("pack_lemonade_4", () -> new PackLemonade4Block());
	public static final RegistryObject<Block> PACK_LEMONADE_8 = REGISTRY.register("pack_lemonade_8", () -> new PackLemonade8Block());
	public static final RegistryObject<Block> PACK_POP_4 = REGISTRY.register("pack_pop_4", () -> new PackPop4Block());
	public static final RegistryObject<Block> PACK_POP_8 = REGISTRY.register("pack_pop_8", () -> new PackPop8Block());
	public static final RegistryObject<Block> PACK_COFFEE_4 = REGISTRY.register("pack_coffee_4", () -> new PackCoffee4Block());
	public static final RegistryObject<Block> PACK_COFFEE_8 = REGISTRY.register("pack_coffee_8", () -> new PackCoffee8Block());
	public static final RegistryObject<Block> PACK_LATTE_4 = REGISTRY.register("pack_latte_4", () -> new PackLatte4Block());
	public static final RegistryObject<Block> PACK_LATTE_8 = REGISTRY.register("pack_latte_8", () -> new PackLatte8Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_0 = REGISTRY.register("calcuim_empty_b_0", () -> new CalcuimEmptyB0Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_1 = REGISTRY.register("calcuim_empty_b_1", () -> new CalcuimEmptyB1Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_2 = REGISTRY.register("calcuim_empty_b_2", () -> new CalcuimEmptyB2Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_3 = REGISTRY.register("calcuim_empty_b_3", () -> new CalcuimEmptyB3Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_4 = REGISTRY.register("calcuim_empty_b_4", () -> new CalcuimEmptyB4Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_5 = REGISTRY.register("calcuim_empty_b_5", () -> new CalcuimEmptyB5Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_6 = REGISTRY.register("calcuim_empty_b_6", () -> new CalcuimEmptyB6Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_7 = REGISTRY.register("calcuim_empty_b_7", () -> new CalcuimEmptyB7Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_8 = REGISTRY.register("calcuim_empty_b_8", () -> new CalcuimEmptyB8Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_9 = REGISTRY.register("calcuim_empty_b_9", () -> new CalcuimEmptyB9Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_10 = REGISTRY.register("calcuim_empty_b_10", () -> new CalcuimEmptyB10Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_11 = REGISTRY.register("calcuim_empty_b_11", () -> new CalcuimEmptyB11Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_12 = REGISTRY.register("calcuim_empty_b_12", () -> new CalcuimEmptyB12Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_13 = REGISTRY.register("calcuim_empty_b_13", () -> new CalcuimEmptyB13Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_14 = REGISTRY.register("calcuim_empty_b_14", () -> new CalcuimEmptyB14Block());
	public static final RegistryObject<Block> CALCUIM_EMPTY_B_15 = REGISTRY.register("calcuim_empty_b_15", () -> new CalcuimEmptyB15Block());
	public static final RegistryObject<Block> CALCUIM_B_0 = REGISTRY.register("calcuim_b_0", () -> new CalcuimB0Block());
	public static final RegistryObject<Block> CALCUIM_B_1 = REGISTRY.register("calcuim_b_1", () -> new CalcuimB1Block());
	public static final RegistryObject<Block> CALCUIM_B_2 = REGISTRY.register("calcuim_b_2", () -> new CalcuimB2Block());
	public static final RegistryObject<Block> CALCUIM_B_3 = REGISTRY.register("calcuim_b_3", () -> new CalcuimB3Block());
	public static final RegistryObject<Block> CALCUIM_B_4 = REGISTRY.register("calcuim_b_4", () -> new CalcuimB4Block());
	public static final RegistryObject<Block> CALCUIM_B_5 = REGISTRY.register("calcuim_b_5", () -> new CalcuimB5Block());
	public static final RegistryObject<Block> CALCUIM_B_6 = REGISTRY.register("calcuim_b_6", () -> new CalcuimB6Block());
	public static final RegistryObject<Block> CALCUIM_B_7 = REGISTRY.register("calcuim_b_7", () -> new CalcuimB7Block());
	public static final RegistryObject<Block> CALCUIM_B_8 = REGISTRY.register("calcuim_b_8", () -> new CalcuimB8Block());
	public static final RegistryObject<Block> CALCUIM_B_9 = REGISTRY.register("calcuim_b_9", () -> new CalcuimB9Block());
	public static final RegistryObject<Block> CALCUIM_B_10 = REGISTRY.register("calcuim_b_10", () -> new CalcuimB10Block());
	public static final RegistryObject<Block> CALCUIM_B_11 = REGISTRY.register("calcuim_b_11", () -> new CalcuimB11Block());
	public static final RegistryObject<Block> CALCUIM_B_12 = REGISTRY.register("calcuim_b_12", () -> new CalcuimB12Block());
	public static final RegistryObject<Block> CALCUIM_B_13 = REGISTRY.register("calcuim_b_13", () -> new CalcuimB13Block());
	public static final RegistryObject<Block> CALCUIM_B_14 = REGISTRY.register("calcuim_b_14", () -> new CalcuimB14Block());
	public static final RegistryObject<Block> CALCUIM_B_15 = REGISTRY.register("calcuim_b_15", () -> new CalcuimB15Block());
}
